// Code generated by ent, DO NOT EDIT.

package event

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDeletedAt, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCategoryID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTitle, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSummary, v))
}

// DescriptionMarkdown applies equality check predicate on the "description_markdown" field. It's identical to DescriptionMarkdownEQ.
func DescriptionMarkdown(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDescriptionMarkdown, v))
}

// OrganizerName applies equality check predicate on the "organizer_name" field. It's identical to OrganizerNameEQ.
func OrganizerName(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldOrganizerName, v))
}

// OrganizerURL applies equality check predicate on the "organizer_url" field. It's identical to OrganizerURLEQ.
func OrganizerURL(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldOrganizerURL, v))
}

// FeeType applies equality check predicate on the "fee_type" field. It's identical to FeeTypeEQ.
func FeeType(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldFeeType, v))
}

// PriceMin applies equality check predicate on the "price_min" field. It's identical to PriceMinEQ.
func PriceMin(v float64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPriceMin, v))
}

// PriceMax applies equality check predicate on the "price_max" field. It's identical to PriceMaxEQ.
func PriceMax(v float64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPriceMax, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCurrency, v))
}

// RegistrationURL applies equality check predicate on the "registration_url" field. It's identical to RegistrationURLEQ.
func RegistrationURL(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRegistrationURL, v))
}

// RegistrationDeadline applies equality check predicate on the "registration_deadline" field. It's identical to RegistrationDeadlineEQ.
func RegistrationDeadline(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRegistrationDeadline, v))
}

// CoverURL applies equality check predicate on the "cover_url" field. It's identical to CoverURLEQ.
func CoverURL(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCoverURL, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStatus, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibility, v))
}

// VisibleFrom applies equality check predicate on the "visible_from" field. It's identical to VisibleFromEQ.
func VisibleFrom(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibleFrom, v))
}

// VisibleUntil applies equality check predicate on the "visible_until" field. It's identical to VisibleUntilEQ.
func VisibleUntil(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibleUntil, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPublishedAt, v))
}

// CancelledReason applies equality check predicate on the "cancelled_reason" field. It's identical to CancelledReasonEQ.
func CancelledReason(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCancelledReason, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldDeletedAt))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldCategoryID))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldTitle, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldSummary, v))
}

// DescriptionMarkdownEQ applies the EQ predicate on the "description_markdown" field.
func DescriptionMarkdownEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownNEQ applies the NEQ predicate on the "description_markdown" field.
func DescriptionMarkdownNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownIn applies the In predicate on the "description_markdown" field.
func DescriptionMarkdownIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldDescriptionMarkdown, vs...))
}

// DescriptionMarkdownNotIn applies the NotIn predicate on the "description_markdown" field.
func DescriptionMarkdownNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldDescriptionMarkdown, vs...))
}

// DescriptionMarkdownGT applies the GT predicate on the "description_markdown" field.
func DescriptionMarkdownGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownGTE applies the GTE predicate on the "description_markdown" field.
func DescriptionMarkdownGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownLT applies the LT predicate on the "description_markdown" field.
func DescriptionMarkdownLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownLTE applies the LTE predicate on the "description_markdown" field.
func DescriptionMarkdownLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownContains applies the Contains predicate on the "description_markdown" field.
func DescriptionMarkdownContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownHasPrefix applies the HasPrefix predicate on the "description_markdown" field.
func DescriptionMarkdownHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownHasSuffix applies the HasSuffix predicate on the "description_markdown" field.
func DescriptionMarkdownHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownEqualFold applies the EqualFold predicate on the "description_markdown" field.
func DescriptionMarkdownEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldDescriptionMarkdown, v))
}

// DescriptionMarkdownContainsFold applies the ContainsFold predicate on the "description_markdown" field.
func DescriptionMarkdownContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldDescriptionMarkdown, v))
}

// OrganizerNameEQ applies the EQ predicate on the "organizer_name" field.
func OrganizerNameEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldOrganizerName, v))
}

// OrganizerNameNEQ applies the NEQ predicate on the "organizer_name" field.
func OrganizerNameNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldOrganizerName, v))
}

// OrganizerNameIn applies the In predicate on the "organizer_name" field.
func OrganizerNameIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldOrganizerName, vs...))
}

// OrganizerNameNotIn applies the NotIn predicate on the "organizer_name" field.
func OrganizerNameNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldOrganizerName, vs...))
}

// OrganizerNameGT applies the GT predicate on the "organizer_name" field.
func OrganizerNameGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldOrganizerName, v))
}

// OrganizerNameGTE applies the GTE predicate on the "organizer_name" field.
func OrganizerNameGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldOrganizerName, v))
}

// OrganizerNameLT applies the LT predicate on the "organizer_name" field.
func OrganizerNameLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldOrganizerName, v))
}

// OrganizerNameLTE applies the LTE predicate on the "organizer_name" field.
func OrganizerNameLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldOrganizerName, v))
}

// OrganizerNameContains applies the Contains predicate on the "organizer_name" field.
func OrganizerNameContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldOrganizerName, v))
}

// OrganizerNameHasPrefix applies the HasPrefix predicate on the "organizer_name" field.
func OrganizerNameHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldOrganizerName, v))
}

// OrganizerNameHasSuffix applies the HasSuffix predicate on the "organizer_name" field.
func OrganizerNameHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldOrganizerName, v))
}

// OrganizerNameEqualFold applies the EqualFold predicate on the "organizer_name" field.
func OrganizerNameEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldOrganizerName, v))
}

// OrganizerNameContainsFold applies the ContainsFold predicate on the "organizer_name" field.
func OrganizerNameContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldOrganizerName, v))
}

// OrganizerURLEQ applies the EQ predicate on the "organizer_url" field.
func OrganizerURLEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldOrganizerURL, v))
}

// OrganizerURLNEQ applies the NEQ predicate on the "organizer_url" field.
func OrganizerURLNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldOrganizerURL, v))
}

// OrganizerURLIn applies the In predicate on the "organizer_url" field.
func OrganizerURLIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldOrganizerURL, vs...))
}

// OrganizerURLNotIn applies the NotIn predicate on the "organizer_url" field.
func OrganizerURLNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldOrganizerURL, vs...))
}

// OrganizerURLGT applies the GT predicate on the "organizer_url" field.
func OrganizerURLGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldOrganizerURL, v))
}

// OrganizerURLGTE applies the GTE predicate on the "organizer_url" field.
func OrganizerURLGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldOrganizerURL, v))
}

// OrganizerURLLT applies the LT predicate on the "organizer_url" field.
func OrganizerURLLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldOrganizerURL, v))
}

// OrganizerURLLTE applies the LTE predicate on the "organizer_url" field.
func OrganizerURLLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldOrganizerURL, v))
}

// OrganizerURLContains applies the Contains predicate on the "organizer_url" field.
func OrganizerURLContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldOrganizerURL, v))
}

// OrganizerURLHasPrefix applies the HasPrefix predicate on the "organizer_url" field.
func OrganizerURLHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldOrganizerURL, v))
}

// OrganizerURLHasSuffix applies the HasSuffix predicate on the "organizer_url" field.
func OrganizerURLHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldOrganizerURL, v))
}

// OrganizerURLEqualFold applies the EqualFold predicate on the "organizer_url" field.
func OrganizerURLEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldOrganizerURL, v))
}

// OrganizerURLContainsFold applies the ContainsFold predicate on the "organizer_url" field.
func OrganizerURLContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldOrganizerURL, v))
}

// FeeTypeEQ applies the EQ predicate on the "fee_type" field.
func FeeTypeEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldFeeType, v))
}

// FeeTypeNEQ applies the NEQ predicate on the "fee_type" field.
func FeeTypeNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldFeeType, v))
}

// FeeTypeIn applies the In predicate on the "fee_type" field.
func FeeTypeIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldFeeType, vs...))
}

// FeeTypeNotIn applies the NotIn predicate on the "fee_type" field.
func FeeTypeNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldFeeType, vs...))
}

// FeeTypeGT applies the GT predicate on the "fee_type" field.
func FeeTypeGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldFeeType, v))
}

// FeeTypeGTE applies the GTE predicate on the "fee_type" field.
func FeeTypeGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldFeeType, v))
}

// FeeTypeLT applies the LT predicate on the "fee_type" field.
func FeeTypeLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldFeeType, v))
}

// FeeTypeLTE applies the LTE predicate on the "fee_type" field.
func FeeTypeLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldFeeType, v))
}

// FeeTypeContains applies the Contains predicate on the "fee_type" field.
func FeeTypeContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldFeeType, v))
}

// FeeTypeHasPrefix applies the HasPrefix predicate on the "fee_type" field.
func FeeTypeHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldFeeType, v))
}

// FeeTypeHasSuffix applies the HasSuffix predicate on the "fee_type" field.
func FeeTypeHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldFeeType, v))
}

// FeeTypeEqualFold applies the EqualFold predicate on the "fee_type" field.
func FeeTypeEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldFeeType, v))
}

// FeeTypeContainsFold applies the ContainsFold predicate on the "fee_type" field.
func FeeTypeContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldFeeType, v))
}

// PriceMinEQ applies the EQ predicate on the "price_min" field.
func PriceMinEQ(v float64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPriceMin, v))
}

// PriceMinNEQ applies the NEQ predicate on the "price_min" field.
func PriceMinNEQ(v float64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldPriceMin, v))
}

// PriceMinIn applies the In predicate on the "price_min" field.
func PriceMinIn(vs ...float64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldPriceMin, vs...))
}

// PriceMinNotIn applies the NotIn predicate on the "price_min" field.
func PriceMinNotIn(vs ...float64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldPriceMin, vs...))
}

// PriceMinGT applies the GT predicate on the "price_min" field.
func PriceMinGT(v float64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldPriceMin, v))
}

// PriceMinGTE applies the GTE predicate on the "price_min" field.
func PriceMinGTE(v float64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldPriceMin, v))
}

// PriceMinLT applies the LT predicate on the "price_min" field.
func PriceMinLT(v float64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldPriceMin, v))
}

// PriceMinLTE applies the LTE predicate on the "price_min" field.
func PriceMinLTE(v float64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldPriceMin, v))
}

// PriceMinIsNil applies the IsNil predicate on the "price_min" field.
func PriceMinIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldPriceMin))
}

// PriceMinNotNil applies the NotNil predicate on the "price_min" field.
func PriceMinNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldPriceMin))
}

// PriceMaxEQ applies the EQ predicate on the "price_max" field.
func PriceMaxEQ(v float64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPriceMax, v))
}

// PriceMaxNEQ applies the NEQ predicate on the "price_max" field.
func PriceMaxNEQ(v float64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldPriceMax, v))
}

// PriceMaxIn applies the In predicate on the "price_max" field.
func PriceMaxIn(vs ...float64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldPriceMax, vs...))
}

// PriceMaxNotIn applies the NotIn predicate on the "price_max" field.
func PriceMaxNotIn(vs ...float64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldPriceMax, vs...))
}

// PriceMaxGT applies the GT predicate on the "price_max" field.
func PriceMaxGT(v float64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldPriceMax, v))
}

// PriceMaxGTE applies the GTE predicate on the "price_max" field.
func PriceMaxGTE(v float64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldPriceMax, v))
}

// PriceMaxLT applies the LT predicate on the "price_max" field.
func PriceMaxLT(v float64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldPriceMax, v))
}

// PriceMaxLTE applies the LTE predicate on the "price_max" field.
func PriceMaxLTE(v float64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldPriceMax, v))
}

// PriceMaxIsNil applies the IsNil predicate on the "price_max" field.
func PriceMaxIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldPriceMax))
}

// PriceMaxNotNil applies the NotNil predicate on the "price_max" field.
func PriceMaxNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldPriceMax))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldCurrency, v))
}

// RegistrationURLEQ applies the EQ predicate on the "registration_url" field.
func RegistrationURLEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRegistrationURL, v))
}

// RegistrationURLNEQ applies the NEQ predicate on the "registration_url" field.
func RegistrationURLNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldRegistrationURL, v))
}

// RegistrationURLIn applies the In predicate on the "registration_url" field.
func RegistrationURLIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldRegistrationURL, vs...))
}

// RegistrationURLNotIn applies the NotIn predicate on the "registration_url" field.
func RegistrationURLNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldRegistrationURL, vs...))
}

// RegistrationURLGT applies the GT predicate on the "registration_url" field.
func RegistrationURLGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldRegistrationURL, v))
}

// RegistrationURLGTE applies the GTE predicate on the "registration_url" field.
func RegistrationURLGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldRegistrationURL, v))
}

// RegistrationURLLT applies the LT predicate on the "registration_url" field.
func RegistrationURLLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldRegistrationURL, v))
}

// RegistrationURLLTE applies the LTE predicate on the "registration_url" field.
func RegistrationURLLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldRegistrationURL, v))
}

// RegistrationURLContains applies the Contains predicate on the "registration_url" field.
func RegistrationURLContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldRegistrationURL, v))
}

// RegistrationURLHasPrefix applies the HasPrefix predicate on the "registration_url" field.
func RegistrationURLHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldRegistrationURL, v))
}

// RegistrationURLHasSuffix applies the HasSuffix predicate on the "registration_url" field.
func RegistrationURLHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldRegistrationURL, v))
}

// RegistrationURLEqualFold applies the EqualFold predicate on the "registration_url" field.
func RegistrationURLEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldRegistrationURL, v))
}

// RegistrationURLContainsFold applies the ContainsFold predicate on the "registration_url" field.
func RegistrationURLContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldRegistrationURL, v))
}

// RegistrationDeadlineEQ applies the EQ predicate on the "registration_deadline" field.
func RegistrationDeadlineEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldRegistrationDeadline, v))
}

// RegistrationDeadlineNEQ applies the NEQ predicate on the "registration_deadline" field.
func RegistrationDeadlineNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldRegistrationDeadline, v))
}

// RegistrationDeadlineIn applies the In predicate on the "registration_deadline" field.
func RegistrationDeadlineIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldRegistrationDeadline, vs...))
}

// RegistrationDeadlineNotIn applies the NotIn predicate on the "registration_deadline" field.
func RegistrationDeadlineNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldRegistrationDeadline, vs...))
}

// RegistrationDeadlineGT applies the GT predicate on the "registration_deadline" field.
func RegistrationDeadlineGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldRegistrationDeadline, v))
}

// RegistrationDeadlineGTE applies the GTE predicate on the "registration_deadline" field.
func RegistrationDeadlineGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldRegistrationDeadline, v))
}

// RegistrationDeadlineLT applies the LT predicate on the "registration_deadline" field.
func RegistrationDeadlineLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldRegistrationDeadline, v))
}

// RegistrationDeadlineLTE applies the LTE predicate on the "registration_deadline" field.
func RegistrationDeadlineLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldRegistrationDeadline, v))
}

// RegistrationDeadlineIsNil applies the IsNil predicate on the "registration_deadline" field.
func RegistrationDeadlineIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldRegistrationDeadline))
}

// RegistrationDeadlineNotNil applies the NotNil predicate on the "registration_deadline" field.
func RegistrationDeadlineNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldRegistrationDeadline))
}

// CoverURLEQ applies the EQ predicate on the "cover_url" field.
func CoverURLEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCoverURL, v))
}

// CoverURLNEQ applies the NEQ predicate on the "cover_url" field.
func CoverURLNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCoverURL, v))
}

// CoverURLIn applies the In predicate on the "cover_url" field.
func CoverURLIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCoverURL, vs...))
}

// CoverURLNotIn applies the NotIn predicate on the "cover_url" field.
func CoverURLNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCoverURL, vs...))
}

// CoverURLGT applies the GT predicate on the "cover_url" field.
func CoverURLGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCoverURL, v))
}

// CoverURLGTE applies the GTE predicate on the "cover_url" field.
func CoverURLGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCoverURL, v))
}

// CoverURLLT applies the LT predicate on the "cover_url" field.
func CoverURLLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCoverURL, v))
}

// CoverURLLTE applies the LTE predicate on the "cover_url" field.
func CoverURLLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCoverURL, v))
}

// CoverURLContains applies the Contains predicate on the "cover_url" field.
func CoverURLContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldCoverURL, v))
}

// CoverURLHasPrefix applies the HasPrefix predicate on the "cover_url" field.
func CoverURLHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldCoverURL, v))
}

// CoverURLHasSuffix applies the HasSuffix predicate on the "cover_url" field.
func CoverURLHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldCoverURL, v))
}

// CoverURLEqualFold applies the EqualFold predicate on the "cover_url" field.
func CoverURLEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldCoverURL, v))
}

// CoverURLContainsFold applies the ContainsFold predicate on the "cover_url" field.
func CoverURLContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldCoverURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldStatus, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldVisibility, v))
}

// VisibleFromEQ applies the EQ predicate on the "visible_from" field.
func VisibleFromEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibleFrom, v))
}

// VisibleFromNEQ applies the NEQ predicate on the "visible_from" field.
func VisibleFromNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldVisibleFrom, v))
}

// VisibleFromIn applies the In predicate on the "visible_from" field.
func VisibleFromIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldVisibleFrom, vs...))
}

// VisibleFromNotIn applies the NotIn predicate on the "visible_from" field.
func VisibleFromNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldVisibleFrom, vs...))
}

// VisibleFromGT applies the GT predicate on the "visible_from" field.
func VisibleFromGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldVisibleFrom, v))
}

// VisibleFromGTE applies the GTE predicate on the "visible_from" field.
func VisibleFromGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldVisibleFrom, v))
}

// VisibleFromLT applies the LT predicate on the "visible_from" field.
func VisibleFromLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldVisibleFrom, v))
}

// VisibleFromLTE applies the LTE predicate on the "visible_from" field.
func VisibleFromLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldVisibleFrom, v))
}

// VisibleFromIsNil applies the IsNil predicate on the "visible_from" field.
func VisibleFromIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldVisibleFrom))
}

// VisibleFromNotNil applies the NotNil predicate on the "visible_from" field.
func VisibleFromNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldVisibleFrom))
}

// VisibleUntilEQ applies the EQ predicate on the "visible_until" field.
func VisibleUntilEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldVisibleUntil, v))
}

// VisibleUntilNEQ applies the NEQ predicate on the "visible_until" field.
func VisibleUntilNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldVisibleUntil, v))
}

// VisibleUntilIn applies the In predicate on the "visible_until" field.
func VisibleUntilIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldVisibleUntil, vs...))
}

// VisibleUntilNotIn applies the NotIn predicate on the "visible_until" field.
func VisibleUntilNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldVisibleUntil, vs...))
}

// VisibleUntilGT applies the GT predicate on the "visible_until" field.
func VisibleUntilGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldVisibleUntil, v))
}

// VisibleUntilGTE applies the GTE predicate on the "visible_until" field.
func VisibleUntilGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldVisibleUntil, v))
}

// VisibleUntilLT applies the LT predicate on the "visible_until" field.
func VisibleUntilLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldVisibleUntil, v))
}

// VisibleUntilLTE applies the LTE predicate on the "visible_until" field.
func VisibleUntilLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldVisibleUntil, v))
}

// VisibleUntilIsNil applies the IsNil predicate on the "visible_until" field.
func VisibleUntilIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldVisibleUntil))
}

// VisibleUntilNotNil applies the NotNil predicate on the "visible_until" field.
func VisibleUntilNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldVisibleUntil))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldPublishedAt))
}

// CancelledReasonEQ applies the EQ predicate on the "cancelled_reason" field.
func CancelledReasonEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCancelledReason, v))
}

// CancelledReasonNEQ applies the NEQ predicate on the "cancelled_reason" field.
func CancelledReasonNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCancelledReason, v))
}

// CancelledReasonIn applies the In predicate on the "cancelled_reason" field.
func CancelledReasonIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCancelledReason, vs...))
}

// CancelledReasonNotIn applies the NotIn predicate on the "cancelled_reason" field.
func CancelledReasonNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCancelledReason, vs...))
}

// CancelledReasonGT applies the GT predicate on the "cancelled_reason" field.
func CancelledReasonGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCancelledReason, v))
}

// CancelledReasonGTE applies the GTE predicate on the "cancelled_reason" field.
func CancelledReasonGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCancelledReason, v))
}

// CancelledReasonLT applies the LT predicate on the "cancelled_reason" field.
func CancelledReasonLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCancelledReason, v))
}

// CancelledReasonLTE applies the LTE predicate on the "cancelled_reason" field.
func CancelledReasonLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCancelledReason, v))
}

// CancelledReasonContains applies the Contains predicate on the "cancelled_reason" field.
func CancelledReasonContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldCancelledReason, v))
}

// CancelledReasonHasPrefix applies the HasPrefix predicate on the "cancelled_reason" field.
func CancelledReasonHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldCancelledReason, v))
}

// CancelledReasonHasSuffix applies the HasSuffix predicate on the "cancelled_reason" field.
func CancelledReasonHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldCancelledReason, v))
}

// CancelledReasonEqualFold applies the EqualFold predicate on the "cancelled_reason" field.
func CancelledReasonEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldCancelledReason, v))
}

// CancelledReasonContainsFold applies the ContainsFold predicate on the "cancelled_reason" field.
func CancelledReasonContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldCancelledReason, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldUpdatedBy))
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.EventCategory) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOccurrences applies the HasEdge predicate on the "occurrences" edge.
func HasOccurrences() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OccurrencesTable, OccurrencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOccurrencesWith applies the HasEdge predicate on the "occurrences" edge with a given conditions (other predicates).
func HasOccurrencesWith(preds ...predicate.EventOccurrence) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newOccurrencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceRecords applies the HasEdge predicate on the "source_records" edge.
func HasSourceRecords() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SourceRecordsTable, SourceRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceRecordsWith applies the HasEdge predicate on the "source_records" edge with a given conditions (other predicates).
func HasSourceRecordsWith(preds ...predicate.EventSourceRecord) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newSourceRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasImportItems applies the HasEdge predicate on the "import_items" edge.
func HasImportItems() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ImportItemsTable, ImportItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImportItemsWith applies the HasEdge predicate on the "import_items" edge with a given conditions (other predicates).
func HasImportItemsWith(preds ...predicate.EventImportItem) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newImportItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Event) predicate.Event {
	return predicate.Event(sql.NotPredicates(p))
}
