// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/eventimportbatch"
	"github.com/Wei-Shaw/sub2api/ent/eventsource"
)

// EventImportBatch is the model entity for the EventImportBatch schema.
type EventImportBatch struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID int64 `json:"source_id,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// FileHash holds the value of the "file_hash" field.
	FileHash string `json:"file_hash,omitempty"`
	// SchemaVersion holds the value of the "schema_version" field.
	SchemaVersion int `json:"schema_version,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// TotalCount holds the value of the "total_count" field.
	TotalCount int `json:"total_count,omitempty"`
	// CreateCount holds the value of the "create_count" field.
	CreateCount int `json:"create_count,omitempty"`
	// UpdateCount holds the value of the "update_count" field.
	UpdateCount int `json:"update_count,omitempty"`
	// UnchangedCount holds the value of the "unchanged_count" field.
	UnchangedCount int `json:"unchanged_count,omitempty"`
	// ConflictCount holds the value of the "conflict_count" field.
	ConflictCount int `json:"conflict_count,omitempty"`
	// ErrorCount holds the value of the "error_count" field.
	ErrorCount int `json:"error_count,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// CommittedAt holds the value of the "committed_at" field.
	CommittedAt *time.Time `json:"committed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventImportBatchQuery when eager-loading is set.
	Edges        EventImportBatchEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventImportBatchEdges holds the relations/edges for other nodes in the graph.
type EventImportBatchEdges struct {
	// Source holds the value of the source edge.
	Source *EventSource `json:"source,omitempty"`
	// Items holds the value of the items edge.
	Items []*EventImportItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventImportBatchEdges) SourceOrErr() (*EventSource, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: eventsource.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e EventImportBatchEdges) ItemsOrErr() ([]*EventImportItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EventImportBatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case eventimportbatch.FieldID, eventimportbatch.FieldSourceID, eventimportbatch.FieldSchemaVersion, eventimportbatch.FieldTotalCount, eventimportbatch.FieldCreateCount, eventimportbatch.FieldUpdateCount, eventimportbatch.FieldUnchangedCount, eventimportbatch.FieldConflictCount, eventimportbatch.FieldErrorCount, eventimportbatch.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case eventimportbatch.FieldFileName, eventimportbatch.FieldFileHash, eventimportbatch.FieldMode, eventimportbatch.FieldStatus:
			values[i] = new(sql.NullString)
		case eventimportbatch.FieldCreatedAt, eventimportbatch.FieldUpdatedAt, eventimportbatch.FieldCommittedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EventImportBatch fields.
func (_m *EventImportBatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case eventimportbatch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case eventimportbatch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case eventimportbatch.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case eventimportbatch.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.Int64
			}
		case eventimportbatch.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case eventimportbatch.FieldFileHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_hash", values[i])
			} else if value.Valid {
				_m.FileHash = value.String
			}
		case eventimportbatch.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				_m.SchemaVersion = int(value.Int64)
			}
		case eventimportbatch.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case eventimportbatch.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case eventimportbatch.FieldTotalCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_count", values[i])
			} else if value.Valid {
				_m.TotalCount = int(value.Int64)
			}
		case eventimportbatch.FieldCreateCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_count", values[i])
			} else if value.Valid {
				_m.CreateCount = int(value.Int64)
			}
		case eventimportbatch.FieldUpdateCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field update_count", values[i])
			} else if value.Valid {
				_m.UpdateCount = int(value.Int64)
			}
		case eventimportbatch.FieldUnchangedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unchanged_count", values[i])
			} else if value.Valid {
				_m.UnchangedCount = int(value.Int64)
			}
		case eventimportbatch.FieldConflictCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conflict_count", values[i])
			} else if value.Valid {
				_m.ConflictCount = int(value.Int64)
			}
		case eventimportbatch.FieldErrorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_count", values[i])
			} else if value.Valid {
				_m.ErrorCount = int(value.Int64)
			}
		case eventimportbatch.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case eventimportbatch.FieldCommittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field committed_at", values[i])
			} else if value.Valid {
				_m.CommittedAt = new(time.Time)
				*_m.CommittedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EventImportBatch.
// This includes values selected through modifiers, order, etc.
func (_m *EventImportBatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySource queries the "source" edge of the EventImportBatch entity.
func (_m *EventImportBatch) QuerySource() *EventSourceQuery {
	return NewEventImportBatchClient(_m.config).QuerySource(_m)
}

// QueryItems queries the "items" edge of the EventImportBatch entity.
func (_m *EventImportBatch) QueryItems() *EventImportItemQuery {
	return NewEventImportBatchClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this EventImportBatch.
// Note that you need to call EventImportBatch.Unwrap() before calling this method if this EventImportBatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EventImportBatch) Update() *EventImportBatchUpdateOne {
	return NewEventImportBatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EventImportBatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EventImportBatch) Unwrap() *EventImportBatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EventImportBatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EventImportBatch) String() string {
	var builder strings.Builder
	builder.WriteString("EventImportBatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("file_hash=")
	builder.WriteString(_m.FileHash)
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.SchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("total_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCount))
	builder.WriteString(", ")
	builder.WriteString("create_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreateCount))
	builder.WriteString(", ")
	builder.WriteString("update_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdateCount))
	builder.WriteString(", ")
	builder.WriteString("unchanged_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnchangedCount))
	builder.WriteString(", ")
	builder.WriteString("conflict_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConflictCount))
	builder.WriteString(", ")
	builder.WriteString("error_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ErrorCount))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	if v := _m.CommittedAt; v != nil {
		builder.WriteString("committed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// EventImportBatches is a parsable slice of EventImportBatch.
type EventImportBatches []*EventImportBatch
