// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/eventimportbatch"
	"github.com/Wei-Shaw/sub2api/ent/eventsource"
	"github.com/Wei-Shaw/sub2api/ent/eventsourcerecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EventSourceUpdate is the builder for updating EventSource entities.
type EventSourceUpdate struct {
	config
	hooks    []Hook
	mutation *EventSourceMutation
}

// Where appends a list predicates to the EventSourceUpdate builder.
func (_u *EventSourceUpdate) Where(ps ...predicate.EventSource) *EventSourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventSourceUpdate) SetUpdatedAt(v time.Time) *EventSourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EventSourceUpdate) SetDeletedAt(v time.Time) *EventSourceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EventSourceUpdate) SetNillableDeletedAt(v *time.Time) *EventSourceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EventSourceUpdate) ClearDeletedAt() *EventSourceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *EventSourceUpdate) SetCode(v string) *EventSourceUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *EventSourceUpdate) SetNillableCode(v *string) *EventSourceUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EventSourceUpdate) SetName(v string) *EventSourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EventSourceUpdate) SetNillableName(v *string) *EventSourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *EventSourceUpdate) SetKind(v string) *EventSourceUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EventSourceUpdate) SetNillableKind(v *string) *EventSourceUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EventSourceUpdate) SetEnabled(v bool) *EventSourceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EventSourceUpdate) SetNillableEnabled(v *bool) *EventSourceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *EventSourceUpdate) SetConfig(v map[string]interface{}) *EventSourceUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *EventSourceUpdate) SetLastSyncAt(v time.Time) *EventSourceUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *EventSourceUpdate) SetNillableLastSyncAt(v *time.Time) *EventSourceUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *EventSourceUpdate) ClearLastSyncAt() *EventSourceUpdate {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// AddRecordIDs adds the "records" edge to the EventSourceRecord entity by IDs.
func (_u *EventSourceUpdate) AddRecordIDs(ids ...int64) *EventSourceUpdate {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the EventSourceRecord entity.
func (_u *EventSourceUpdate) AddRecords(v ...*EventSourceRecord) *EventSourceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// AddImportBatchIDs adds the "import_batches" edge to the EventImportBatch entity by IDs.
func (_u *EventSourceUpdate) AddImportBatchIDs(ids ...int64) *EventSourceUpdate {
	_u.mutation.AddImportBatchIDs(ids...)
	return _u
}

// AddImportBatches adds the "import_batches" edges to the EventImportBatch entity.
func (_u *EventSourceUpdate) AddImportBatches(v ...*EventImportBatch) *EventSourceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImportBatchIDs(ids...)
}

// Mutation returns the EventSourceMutation object of the builder.
func (_u *EventSourceUpdate) Mutation() *EventSourceMutation {
	return _u.mutation
}

// ClearRecords clears all "records" edges to the EventSourceRecord entity.
func (_u *EventSourceUpdate) ClearRecords() *EventSourceUpdate {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to EventSourceRecord entities by IDs.
func (_u *EventSourceUpdate) RemoveRecordIDs(ids ...int64) *EventSourceUpdate {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to EventSourceRecord entities.
func (_u *EventSourceUpdate) RemoveRecords(v ...*EventSourceRecord) *EventSourceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// ClearImportBatches clears all "import_batches" edges to the EventImportBatch entity.
func (_u *EventSourceUpdate) ClearImportBatches() *EventSourceUpdate {
	_u.mutation.ClearImportBatches()
	return _u
}

// RemoveImportBatchIDs removes the "import_batches" edge to EventImportBatch entities by IDs.
func (_u *EventSourceUpdate) RemoveImportBatchIDs(ids ...int64) *EventSourceUpdate {
	_u.mutation.RemoveImportBatchIDs(ids...)
	return _u
}

// RemoveImportBatches removes "import_batches" edges to EventImportBatch entities.
func (_u *EventSourceUpdate) RemoveImportBatches(v ...*EventImportBatch) *EventSourceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImportBatchIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventSourceUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventSourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventSourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventSourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventSourceUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if eventsource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized eventsource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := eventsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventSourceUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := eventsource.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EventSource.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := eventsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EventSource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := eventsource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EventSource.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *EventSourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventsource.Table, eventsource.Columns, sqlgraph.NewFieldSpec(eventsource.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(eventsource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(eventsource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(eventsource.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(eventsource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(eventsource.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(eventsource.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(eventsource.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(eventsource.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(eventsource.FieldLastSyncAt, field.TypeTime)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.RecordsTable,
			Columns: []string{eventsource.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.RecordsTable,
			Columns: []string{eventsource.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.RecordsTable,
			Columns: []string{eventsource.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImportBatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.ImportBatchesTable,
			Columns: []string{eventsource.ImportBatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImportBatchesIDs(); len(nodes) > 0 && !_u.mutation.ImportBatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.ImportBatchesTable,
			Columns: []string{eventsource.ImportBatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImportBatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.ImportBatchesTable,
			Columns: []string{eventsource.ImportBatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventSourceUpdateOne is the builder for updating a single EventSource entity.
type EventSourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventSourceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventSourceUpdateOne) SetUpdatedAt(v time.Time) *EventSourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EventSourceUpdateOne) SetDeletedAt(v time.Time) *EventSourceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EventSourceUpdateOne) SetNillableDeletedAt(v *time.Time) *EventSourceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EventSourceUpdateOne) ClearDeletedAt() *EventSourceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *EventSourceUpdateOne) SetCode(v string) *EventSourceUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *EventSourceUpdateOne) SetNillableCode(v *string) *EventSourceUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EventSourceUpdateOne) SetName(v string) *EventSourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EventSourceUpdateOne) SetNillableName(v *string) *EventSourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *EventSourceUpdateOne) SetKind(v string) *EventSourceUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EventSourceUpdateOne) SetNillableKind(v *string) *EventSourceUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *EventSourceUpdateOne) SetEnabled(v bool) *EventSourceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *EventSourceUpdateOne) SetNillableEnabled(v *bool) *EventSourceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *EventSourceUpdateOne) SetConfig(v map[string]interface{}) *EventSourceUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *EventSourceUpdateOne) SetLastSyncAt(v time.Time) *EventSourceUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *EventSourceUpdateOne) SetNillableLastSyncAt(v *time.Time) *EventSourceUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *EventSourceUpdateOne) ClearLastSyncAt() *EventSourceUpdateOne {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// AddRecordIDs adds the "records" edge to the EventSourceRecord entity by IDs.
func (_u *EventSourceUpdateOne) AddRecordIDs(ids ...int64) *EventSourceUpdateOne {
	_u.mutation.AddRecordIDs(ids...)
	return _u
}

// AddRecords adds the "records" edges to the EventSourceRecord entity.
func (_u *EventSourceUpdateOne) AddRecords(v ...*EventSourceRecord) *EventSourceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecordIDs(ids...)
}

// AddImportBatchIDs adds the "import_batches" edge to the EventImportBatch entity by IDs.
func (_u *EventSourceUpdateOne) AddImportBatchIDs(ids ...int64) *EventSourceUpdateOne {
	_u.mutation.AddImportBatchIDs(ids...)
	return _u
}

// AddImportBatches adds the "import_batches" edges to the EventImportBatch entity.
func (_u *EventSourceUpdateOne) AddImportBatches(v ...*EventImportBatch) *EventSourceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImportBatchIDs(ids...)
}

// Mutation returns the EventSourceMutation object of the builder.
func (_u *EventSourceUpdateOne) Mutation() *EventSourceMutation {
	return _u.mutation
}

// ClearRecords clears all "records" edges to the EventSourceRecord entity.
func (_u *EventSourceUpdateOne) ClearRecords() *EventSourceUpdateOne {
	_u.mutation.ClearRecords()
	return _u
}

// RemoveRecordIDs removes the "records" edge to EventSourceRecord entities by IDs.
func (_u *EventSourceUpdateOne) RemoveRecordIDs(ids ...int64) *EventSourceUpdateOne {
	_u.mutation.RemoveRecordIDs(ids...)
	return _u
}

// RemoveRecords removes "records" edges to EventSourceRecord entities.
func (_u *EventSourceUpdateOne) RemoveRecords(v ...*EventSourceRecord) *EventSourceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecordIDs(ids...)
}

// ClearImportBatches clears all "import_batches" edges to the EventImportBatch entity.
func (_u *EventSourceUpdateOne) ClearImportBatches() *EventSourceUpdateOne {
	_u.mutation.ClearImportBatches()
	return _u
}

// RemoveImportBatchIDs removes the "import_batches" edge to EventImportBatch entities by IDs.
func (_u *EventSourceUpdateOne) RemoveImportBatchIDs(ids ...int64) *EventSourceUpdateOne {
	_u.mutation.RemoveImportBatchIDs(ids...)
	return _u
}

// RemoveImportBatches removes "import_batches" edges to EventImportBatch entities.
func (_u *EventSourceUpdateOne) RemoveImportBatches(v ...*EventImportBatch) *EventSourceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImportBatchIDs(ids...)
}

// Where appends a list predicates to the EventSourceUpdate builder.
func (_u *EventSourceUpdateOne) Where(ps ...predicate.EventSource) *EventSourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventSourceUpdateOne) Select(field string, fields ...string) *EventSourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EventSource entity.
func (_u *EventSourceUpdateOne) Save(ctx context.Context) (*EventSource, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventSourceUpdateOne) SaveX(ctx context.Context) *EventSource {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventSourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventSourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventSourceUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if eventsource.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized eventsource.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := eventsource.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventSourceUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := eventsource.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EventSource.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := eventsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EventSource.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := eventsource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EventSource.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *EventSourceUpdateOne) sqlSave(ctx context.Context) (_node *EventSource, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventsource.Table, eventsource.Columns, sqlgraph.NewFieldSpec(eventsource.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventSource.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventsource.FieldID)
		for _, f := range fields {
			if !eventsource.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(eventsource.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(eventsource.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(eventsource.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(eventsource.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(eventsource.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(eventsource.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(eventsource.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(eventsource.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(eventsource.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(eventsource.FieldLastSyncAt, field.TypeTime)
	}
	if _u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.RecordsTable,
			Columns: []string{eventsource.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecordsIDs(); len(nodes) > 0 && !_u.mutation.RecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.RecordsTable,
			Columns: []string{eventsource.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.RecordsTable,
			Columns: []string{eventsource.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImportBatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.ImportBatchesTable,
			Columns: []string{eventsource.ImportBatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImportBatchesIDs(); len(nodes) > 0 && !_u.mutation.ImportBatchesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.ImportBatchesTable,
			Columns: []string{eventsource.ImportBatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImportBatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.ImportBatchesTable,
			Columns: []string{eventsource.ImportBatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EventSource{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventsource.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
