// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/eventimportbatch"
	"github.com/Wei-Shaw/sub2api/ent/eventsource"
	"github.com/Wei-Shaw/sub2api/ent/eventsourcerecord"
)

// EventSourceCreate is the builder for creating a EventSource entity.
type EventSourceCreate struct {
	config
	mutation *EventSourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventSourceCreate) SetCreatedAt(v time.Time) *EventSourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventSourceCreate) SetNillableCreatedAt(v *time.Time) *EventSourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventSourceCreate) SetUpdatedAt(v time.Time) *EventSourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventSourceCreate) SetNillableUpdatedAt(v *time.Time) *EventSourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EventSourceCreate) SetDeletedAt(v time.Time) *EventSourceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EventSourceCreate) SetNillableDeletedAt(v *time.Time) *EventSourceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *EventSourceCreate) SetCode(v string) *EventSourceCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *EventSourceCreate) SetName(v string) *EventSourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *EventSourceCreate) SetKind(v string) *EventSourceCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *EventSourceCreate) SetNillableKind(v *string) *EventSourceCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *EventSourceCreate) SetEnabled(v bool) *EventSourceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *EventSourceCreate) SetNillableEnabled(v *bool) *EventSourceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *EventSourceCreate) SetConfig(v map[string]interface{}) *EventSourceCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_c *EventSourceCreate) SetLastSyncAt(v time.Time) *EventSourceCreate {
	_c.mutation.SetLastSyncAt(v)
	return _c
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_c *EventSourceCreate) SetNillableLastSyncAt(v *time.Time) *EventSourceCreate {
	if v != nil {
		_c.SetLastSyncAt(*v)
	}
	return _c
}

// AddRecordIDs adds the "records" edge to the EventSourceRecord entity by IDs.
func (_c *EventSourceCreate) AddRecordIDs(ids ...int64) *EventSourceCreate {
	_c.mutation.AddRecordIDs(ids...)
	return _c
}

// AddRecords adds the "records" edges to the EventSourceRecord entity.
func (_c *EventSourceCreate) AddRecords(v ...*EventSourceRecord) *EventSourceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecordIDs(ids...)
}

// AddImportBatchIDs adds the "import_batches" edge to the EventImportBatch entity by IDs.
func (_c *EventSourceCreate) AddImportBatchIDs(ids ...int64) *EventSourceCreate {
	_c.mutation.AddImportBatchIDs(ids...)
	return _c
}

// AddImportBatches adds the "import_batches" edges to the EventImportBatch entity.
func (_c *EventSourceCreate) AddImportBatches(v ...*EventImportBatch) *EventSourceCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddImportBatchIDs(ids...)
}

// Mutation returns the EventSourceMutation object of the builder.
func (_c *EventSourceCreate) Mutation() *EventSourceMutation {
	return _c.mutation
}

// Save creates the EventSource in the database.
func (_c *EventSourceCreate) Save(ctx context.Context) (*EventSource, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventSourceCreate) SaveX(ctx context.Context) *EventSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventSourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventSourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventSourceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if eventsource.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized eventsource.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := eventsource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if eventsource.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized eventsource.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := eventsource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := eventsource.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := eventsource.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Config(); !ok {
		v := eventsource.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventSourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventSource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventSource.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "EventSource.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := eventsource.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "EventSource.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EventSource.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := eventsource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EventSource.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "EventSource.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := eventsource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EventSource.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "EventSource.enabled"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "EventSource.config"`)}
	}
	return nil
}

func (_c *EventSourceCreate) sqlSave(ctx context.Context) (*EventSource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventSourceCreate) createSpec() (*EventSource, *sqlgraph.CreateSpec) {
	var (
		_node = &EventSource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventsource.Table, sqlgraph.NewFieldSpec(eventsource.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(eventsource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(eventsource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(eventsource.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(eventsource.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(eventsource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(eventsource.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(eventsource.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(eventsource.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.LastSyncAt(); ok {
		_spec.SetField(eventsource.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = &value
	}
	if nodes := _c.mutation.RecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.RecordsTable,
			Columns: []string{eventsource.RecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ImportBatchesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventsource.ImportBatchesTable,
			Columns: []string{eventsource.ImportBatchesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EventSource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventSourceCreate) OnConflict(opts ...sql.ConflictOption) *EventSourceUpsertOne {
	_c.conflict = opts
	return &EventSourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EventSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventSourceCreate) OnConflictColumns(columns ...string) *EventSourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventSourceUpsertOne{
		create: _c,
	}
}

type (
	// EventSourceUpsertOne is the builder for "upsert"-ing
	//  one EventSource node.
	EventSourceUpsertOne struct {
		create *EventSourceCreate
	}

	// EventSourceUpsert is the "OnConflict" setter.
	EventSourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EventSourceUpsert) SetUpdatedAt(v time.Time) *EventSourceUpsert {
	u.Set(eventsource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateUpdatedAt() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventSourceUpsert) SetDeletedAt(v time.Time) *EventSourceUpsert {
	u.Set(eventsource.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateDeletedAt() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventSourceUpsert) ClearDeletedAt() *EventSourceUpsert {
	u.SetNull(eventsource.FieldDeletedAt)
	return u
}

// SetCode sets the "code" field.
func (u *EventSourceUpsert) SetCode(v string) *EventSourceUpsert {
	u.Set(eventsource.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateCode() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *EventSourceUpsert) SetName(v string) *EventSourceUpsert {
	u.Set(eventsource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateName() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldName)
	return u
}

// SetKind sets the "kind" field.
func (u *EventSourceUpsert) SetKind(v string) *EventSourceUpsert {
	u.Set(eventsource.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateKind() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldKind)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *EventSourceUpsert) SetEnabled(v bool) *EventSourceUpsert {
	u.Set(eventsource.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateEnabled() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldEnabled)
	return u
}

// SetConfig sets the "config" field.
func (u *EventSourceUpsert) SetConfig(v map[string]interface{}) *EventSourceUpsert {
	u.Set(eventsource.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateConfig() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldConfig)
	return u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *EventSourceUpsert) SetLastSyncAt(v time.Time) *EventSourceUpsert {
	u.Set(eventsource.FieldLastSyncAt, v)
	return u
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *EventSourceUpsert) UpdateLastSyncAt() *EventSourceUpsert {
	u.SetExcluded(eventsource.FieldLastSyncAt)
	return u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *EventSourceUpsert) ClearLastSyncAt() *EventSourceUpsert {
	u.SetNull(eventsource.FieldLastSyncAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EventSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventSourceUpsertOne) UpdateNewValues() *EventSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(eventsource.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EventSource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EventSourceUpsertOne) Ignore() *EventSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventSourceUpsertOne) DoNothing() *EventSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventSourceCreate.OnConflict
// documentation for more info.
func (u *EventSourceUpsertOne) Update(set func(*EventSourceUpsert)) *EventSourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventSourceUpsertOne) SetUpdatedAt(v time.Time) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateUpdatedAt() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventSourceUpsertOne) SetDeletedAt(v time.Time) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateDeletedAt() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventSourceUpsertOne) ClearDeletedAt() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *EventSourceUpsertOne) SetCode(v string) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateCode() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *EventSourceUpsertOne) SetName(v string) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateName() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *EventSourceUpsertOne) SetKind(v string) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateKind() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateKind()
	})
}

// SetEnabled sets the "enabled" field.
func (u *EventSourceUpsertOne) SetEnabled(v bool) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateEnabled() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateEnabled()
	})
}

// SetConfig sets the "config" field.
func (u *EventSourceUpsertOne) SetConfig(v map[string]interface{}) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateConfig() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateConfig()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *EventSourceUpsertOne) SetLastSyncAt(v time.Time) *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *EventSourceUpsertOne) UpdateLastSyncAt() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *EventSourceUpsertOne) ClearLastSyncAt() *EventSourceUpsertOne {
	return u.Update(func(s *EventSourceUpsert) {
		s.ClearLastSyncAt()
	})
}

// Exec executes the query.
func (u *EventSourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventSourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventSourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EventSourceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EventSourceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EventSourceCreateBulk is the builder for creating many EventSource entities in bulk.
type EventSourceCreateBulk struct {
	config
	err      error
	builders []*EventSourceCreate
	conflict []sql.ConflictOption
}

// Save creates the EventSource entities in the database.
func (_c *EventSourceCreateBulk) Save(ctx context.Context) ([]*EventSource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventSource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventSourceCreateBulk) SaveX(ctx context.Context) []*EventSource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventSourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EventSource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventSourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventSourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *EventSourceUpsertBulk {
	_c.conflict = opts
	return &EventSourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EventSource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventSourceCreateBulk) OnConflictColumns(columns ...string) *EventSourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventSourceUpsertBulk{
		create: _c,
	}
}

// EventSourceUpsertBulk is the builder for "upsert"-ing
// a bulk of EventSource nodes.
type EventSourceUpsertBulk struct {
	create *EventSourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EventSource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventSourceUpsertBulk) UpdateNewValues() *EventSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(eventsource.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EventSource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EventSourceUpsertBulk) Ignore() *EventSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventSourceUpsertBulk) DoNothing() *EventSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventSourceCreateBulk.OnConflict
// documentation for more info.
func (u *EventSourceUpsertBulk) Update(set func(*EventSourceUpsert)) *EventSourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventSourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventSourceUpsertBulk) SetUpdatedAt(v time.Time) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateUpdatedAt() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventSourceUpsertBulk) SetDeletedAt(v time.Time) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateDeletedAt() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventSourceUpsertBulk) ClearDeletedAt() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *EventSourceUpsertBulk) SetCode(v string) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateCode() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *EventSourceUpsertBulk) SetName(v string) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateName() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *EventSourceUpsertBulk) SetKind(v string) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateKind() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateKind()
	})
}

// SetEnabled sets the "enabled" field.
func (u *EventSourceUpsertBulk) SetEnabled(v bool) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateEnabled() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateEnabled()
	})
}

// SetConfig sets the "config" field.
func (u *EventSourceUpsertBulk) SetConfig(v map[string]interface{}) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateConfig() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateConfig()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *EventSourceUpsertBulk) SetLastSyncAt(v time.Time) *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *EventSourceUpsertBulk) UpdateLastSyncAt() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *EventSourceUpsertBulk) ClearLastSyncAt() *EventSourceUpsertBulk {
	return u.Update(func(s *EventSourceUpsert) {
		s.ClearLastSyncAt()
	})
}

// Exec executes the query.
func (u *EventSourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EventSourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventSourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventSourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
