// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/event"
	"github.com/Wei-Shaw/sub2api/ent/eventcategory"
	"github.com/Wei-Shaw/sub2api/ent/eventimportitem"
	"github.com/Wei-Shaw/sub2api/ent/eventoccurrence"
	"github.com/Wei-Shaw/sub2api/ent/eventsourcerecord"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventCreate) SetCreatedAt(v time.Time) *EventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableCreatedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventCreate) SetUpdatedAt(v time.Time) *EventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableUpdatedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EventCreate) SetDeletedAt(v time.Time) *EventCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableDeletedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *EventCreate) SetCategoryID(v int64) *EventCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableCategoryID(v *int64) *EventCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *EventCreate) SetTitle(v string) *EventCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *EventCreate) SetSummary(v string) *EventCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *EventCreate) SetNillableSummary(v *string) *EventCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetDescriptionMarkdown sets the "description_markdown" field.
func (_c *EventCreate) SetDescriptionMarkdown(v string) *EventCreate {
	_c.mutation.SetDescriptionMarkdown(v)
	return _c
}

// SetNillableDescriptionMarkdown sets the "description_markdown" field if the given value is not nil.
func (_c *EventCreate) SetNillableDescriptionMarkdown(v *string) *EventCreate {
	if v != nil {
		_c.SetDescriptionMarkdown(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *EventCreate) SetTags(v []string) *EventCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetOrganizerName sets the "organizer_name" field.
func (_c *EventCreate) SetOrganizerName(v string) *EventCreate {
	_c.mutation.SetOrganizerName(v)
	return _c
}

// SetNillableOrganizerName sets the "organizer_name" field if the given value is not nil.
func (_c *EventCreate) SetNillableOrganizerName(v *string) *EventCreate {
	if v != nil {
		_c.SetOrganizerName(*v)
	}
	return _c
}

// SetOrganizerURL sets the "organizer_url" field.
func (_c *EventCreate) SetOrganizerURL(v string) *EventCreate {
	_c.mutation.SetOrganizerURL(v)
	return _c
}

// SetNillableOrganizerURL sets the "organizer_url" field if the given value is not nil.
func (_c *EventCreate) SetNillableOrganizerURL(v *string) *EventCreate {
	if v != nil {
		_c.SetOrganizerURL(*v)
	}
	return _c
}

// SetFeeType sets the "fee_type" field.
func (_c *EventCreate) SetFeeType(v string) *EventCreate {
	_c.mutation.SetFeeType(v)
	return _c
}

// SetNillableFeeType sets the "fee_type" field if the given value is not nil.
func (_c *EventCreate) SetNillableFeeType(v *string) *EventCreate {
	if v != nil {
		_c.SetFeeType(*v)
	}
	return _c
}

// SetPriceMin sets the "price_min" field.
func (_c *EventCreate) SetPriceMin(v float64) *EventCreate {
	_c.mutation.SetPriceMin(v)
	return _c
}

// SetNillablePriceMin sets the "price_min" field if the given value is not nil.
func (_c *EventCreate) SetNillablePriceMin(v *float64) *EventCreate {
	if v != nil {
		_c.SetPriceMin(*v)
	}
	return _c
}

// SetPriceMax sets the "price_max" field.
func (_c *EventCreate) SetPriceMax(v float64) *EventCreate {
	_c.mutation.SetPriceMax(v)
	return _c
}

// SetNillablePriceMax sets the "price_max" field if the given value is not nil.
func (_c *EventCreate) SetNillablePriceMax(v *float64) *EventCreate {
	if v != nil {
		_c.SetPriceMax(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *EventCreate) SetCurrency(v string) *EventCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *EventCreate) SetNillableCurrency(v *string) *EventCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetRegistrationURL sets the "registration_url" field.
func (_c *EventCreate) SetRegistrationURL(v string) *EventCreate {
	_c.mutation.SetRegistrationURL(v)
	return _c
}

// SetNillableRegistrationURL sets the "registration_url" field if the given value is not nil.
func (_c *EventCreate) SetNillableRegistrationURL(v *string) *EventCreate {
	if v != nil {
		_c.SetRegistrationURL(*v)
	}
	return _c
}

// SetRegistrationDeadline sets the "registration_deadline" field.
func (_c *EventCreate) SetRegistrationDeadline(v time.Time) *EventCreate {
	_c.mutation.SetRegistrationDeadline(v)
	return _c
}

// SetNillableRegistrationDeadline sets the "registration_deadline" field if the given value is not nil.
func (_c *EventCreate) SetNillableRegistrationDeadline(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetRegistrationDeadline(*v)
	}
	return _c
}

// SetCoverURL sets the "cover_url" field.
func (_c *EventCreate) SetCoverURL(v string) *EventCreate {
	_c.mutation.SetCoverURL(v)
	return _c
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_c *EventCreate) SetNillableCoverURL(v *string) *EventCreate {
	if v != nil {
		_c.SetCoverURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EventCreate) SetStatus(v string) *EventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventCreate) SetNillableStatus(v *string) *EventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *EventCreate) SetVisibility(v string) *EventCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *EventCreate) SetNillableVisibility(v *string) *EventCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetAudience sets the "audience" field.
func (_c *EventCreate) SetAudience(v domain.EventAudience) *EventCreate {
	_c.mutation.SetAudience(v)
	return _c
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_c *EventCreate) SetNillableAudience(v *domain.EventAudience) *EventCreate {
	if v != nil {
		_c.SetAudience(*v)
	}
	return _c
}

// SetVisibleFrom sets the "visible_from" field.
func (_c *EventCreate) SetVisibleFrom(v time.Time) *EventCreate {
	_c.mutation.SetVisibleFrom(v)
	return _c
}

// SetNillableVisibleFrom sets the "visible_from" field if the given value is not nil.
func (_c *EventCreate) SetNillableVisibleFrom(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetVisibleFrom(*v)
	}
	return _c
}

// SetVisibleUntil sets the "visible_until" field.
func (_c *EventCreate) SetVisibleUntil(v time.Time) *EventCreate {
	_c.mutation.SetVisibleUntil(v)
	return _c
}

// SetNillableVisibleUntil sets the "visible_until" field if the given value is not nil.
func (_c *EventCreate) SetNillableVisibleUntil(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetVisibleUntil(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *EventCreate) SetPublishedAt(v time.Time) *EventCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *EventCreate) SetNillablePublishedAt(v *time.Time) *EventCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCancelledReason sets the "cancelled_reason" field.
func (_c *EventCreate) SetCancelledReason(v string) *EventCreate {
	_c.mutation.SetCancelledReason(v)
	return _c
}

// SetNillableCancelledReason sets the "cancelled_reason" field if the given value is not nil.
func (_c *EventCreate) SetNillableCancelledReason(v *string) *EventCreate {
	if v != nil {
		_c.SetCancelledReason(*v)
	}
	return _c
}

// SetManualOverrideFields sets the "manual_override_fields" field.
func (_c *EventCreate) SetManualOverrideFields(v []string) *EventCreate {
	_c.mutation.SetManualOverrideFields(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EventCreate) SetCreatedBy(v int64) *EventCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *EventCreate) SetNillableCreatedBy(v *int64) *EventCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *EventCreate) SetUpdatedBy(v int64) *EventCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *EventCreate) SetNillableUpdatedBy(v *int64) *EventCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCategory sets the "category" edge to the EventCategory entity.
func (_c *EventCreate) SetCategory(v *EventCategory) *EventCreate {
	return _c.SetCategoryID(v.ID)
}

// AddOccurrenceIDs adds the "occurrences" edge to the EventOccurrence entity by IDs.
func (_c *EventCreate) AddOccurrenceIDs(ids ...int64) *EventCreate {
	_c.mutation.AddOccurrenceIDs(ids...)
	return _c
}

// AddOccurrences adds the "occurrences" edges to the EventOccurrence entity.
func (_c *EventCreate) AddOccurrences(v ...*EventOccurrence) *EventCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOccurrenceIDs(ids...)
}

// AddSourceRecordIDs adds the "source_records" edge to the EventSourceRecord entity by IDs.
func (_c *EventCreate) AddSourceRecordIDs(ids ...int64) *EventCreate {
	_c.mutation.AddSourceRecordIDs(ids...)
	return _c
}

// AddSourceRecords adds the "source_records" edges to the EventSourceRecord entity.
func (_c *EventCreate) AddSourceRecords(v ...*EventSourceRecord) *EventCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSourceRecordIDs(ids...)
}

// AddImportItemIDs adds the "import_items" edge to the EventImportItem entity by IDs.
func (_c *EventCreate) AddImportItemIDs(ids ...int64) *EventCreate {
	_c.mutation.AddImportItemIDs(ids...)
	return _c
}

// AddImportItems adds the "import_items" edges to the EventImportItem entity.
func (_c *EventCreate) AddImportItems(v ...*EventImportItem) *EventCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddImportItemIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if event.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := event.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if event.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := event.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := event.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.DescriptionMarkdown(); !ok {
		v := event.DefaultDescriptionMarkdown
		_c.mutation.SetDescriptionMarkdown(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := event.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.OrganizerName(); !ok {
		v := event.DefaultOrganizerName
		_c.mutation.SetOrganizerName(v)
	}
	if _, ok := _c.mutation.OrganizerURL(); !ok {
		v := event.DefaultOrganizerURL
		_c.mutation.SetOrganizerURL(v)
	}
	if _, ok := _c.mutation.FeeType(); !ok {
		v := event.DefaultFeeType
		_c.mutation.SetFeeType(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := event.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.RegistrationURL(); !ok {
		v := event.DefaultRegistrationURL
		_c.mutation.SetRegistrationURL(v)
	}
	if _, ok := _c.mutation.CoverURL(); !ok {
		v := event.DefaultCoverURL
		_c.mutation.SetCoverURL(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := event.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := event.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Audience(); !ok {
		v := event.DefaultAudience
		_c.mutation.SetAudience(v)
	}
	if _, ok := _c.mutation.CancelledReason(); !ok {
		v := event.DefaultCancelledReason
		_c.mutation.SetCancelledReason(v)
	}
	if _, ok := _c.mutation.ManualOverrideFields(); !ok {
		v := event.DefaultManualOverrideFields
		_c.mutation.SetManualOverrideFields(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Event.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Event.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Event.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := event.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Event.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Event.summary"`)}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := event.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Event.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DescriptionMarkdown(); !ok {
		return &ValidationError{Name: "description_markdown", err: errors.New(`ent: missing required field "Event.description_markdown"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Event.tags"`)}
	}
	if _, ok := _c.mutation.OrganizerName(); !ok {
		return &ValidationError{Name: "organizer_name", err: errors.New(`ent: missing required field "Event.organizer_name"`)}
	}
	if v, ok := _c.mutation.OrganizerName(); ok {
		if err := event.OrganizerNameValidator(v); err != nil {
			return &ValidationError{Name: "organizer_name", err: fmt.Errorf(`ent: validator failed for field "Event.organizer_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrganizerURL(); !ok {
		return &ValidationError{Name: "organizer_url", err: errors.New(`ent: missing required field "Event.organizer_url"`)}
	}
	if v, ok := _c.mutation.OrganizerURL(); ok {
		if err := event.OrganizerURLValidator(v); err != nil {
			return &ValidationError{Name: "organizer_url", err: fmt.Errorf(`ent: validator failed for field "Event.organizer_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FeeType(); !ok {
		return &ValidationError{Name: "fee_type", err: errors.New(`ent: missing required field "Event.fee_type"`)}
	}
	if v, ok := _c.mutation.FeeType(); ok {
		if err := event.FeeTypeValidator(v); err != nil {
			return &ValidationError{Name: "fee_type", err: fmt.Errorf(`ent: validator failed for field "Event.fee_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Event.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := event.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Event.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RegistrationURL(); !ok {
		return &ValidationError{Name: "registration_url", err: errors.New(`ent: missing required field "Event.registration_url"`)}
	}
	if v, ok := _c.mutation.RegistrationURL(); ok {
		if err := event.RegistrationURLValidator(v); err != nil {
			return &ValidationError{Name: "registration_url", err: fmt.Errorf(`ent: validator failed for field "Event.registration_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CoverURL(); !ok {
		return &ValidationError{Name: "cover_url", err: errors.New(`ent: missing required field "Event.cover_url"`)}
	}
	if v, ok := _c.mutation.CoverURL(); ok {
		if err := event.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Event.cover_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Event.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := event.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Event.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "Event.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := event.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Event.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Audience(); !ok {
		return &ValidationError{Name: "audience", err: errors.New(`ent: missing required field "Event.audience"`)}
	}
	if _, ok := _c.mutation.CancelledReason(); !ok {
		return &ValidationError{Name: "cancelled_reason", err: errors.New(`ent: missing required field "Event.cancelled_reason"`)}
	}
	if v, ok := _c.mutation.CancelledReason(); ok {
		if err := event.CancelledReasonValidator(v); err != nil {
			return &ValidationError{Name: "cancelled_reason", err: fmt.Errorf(`ent: validator failed for field "Event.cancelled_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManualOverrideFields(); !ok {
		return &ValidationError{Name: "manual_override_fields", err: errors.New(`ent: missing required field "Event.manual_override_fields"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(event.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(event.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(event.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.DescriptionMarkdown(); ok {
		_spec.SetField(event.FieldDescriptionMarkdown, field.TypeString, value)
		_node.DescriptionMarkdown = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(event.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.OrganizerName(); ok {
		_spec.SetField(event.FieldOrganizerName, field.TypeString, value)
		_node.OrganizerName = value
	}
	if value, ok := _c.mutation.OrganizerURL(); ok {
		_spec.SetField(event.FieldOrganizerURL, field.TypeString, value)
		_node.OrganizerURL = value
	}
	if value, ok := _c.mutation.FeeType(); ok {
		_spec.SetField(event.FieldFeeType, field.TypeString, value)
		_node.FeeType = value
	}
	if value, ok := _c.mutation.PriceMin(); ok {
		_spec.SetField(event.FieldPriceMin, field.TypeFloat64, value)
		_node.PriceMin = &value
	}
	if value, ok := _c.mutation.PriceMax(); ok {
		_spec.SetField(event.FieldPriceMax, field.TypeFloat64, value)
		_node.PriceMax = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(event.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RegistrationURL(); ok {
		_spec.SetField(event.FieldRegistrationURL, field.TypeString, value)
		_node.RegistrationURL = value
	}
	if value, ok := _c.mutation.RegistrationDeadline(); ok {
		_spec.SetField(event.FieldRegistrationDeadline, field.TypeTime, value)
		_node.RegistrationDeadline = &value
	}
	if value, ok := _c.mutation.CoverURL(); ok {
		_spec.SetField(event.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(event.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(event.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Audience(); ok {
		_spec.SetField(event.FieldAudience, field.TypeJSON, value)
		_node.Audience = value
	}
	if value, ok := _c.mutation.VisibleFrom(); ok {
		_spec.SetField(event.FieldVisibleFrom, field.TypeTime, value)
		_node.VisibleFrom = &value
	}
	if value, ok := _c.mutation.VisibleUntil(); ok {
		_spec.SetField(event.FieldVisibleUntil, field.TypeTime, value)
		_node.VisibleUntil = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(event.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.CancelledReason(); ok {
		_spec.SetField(event.FieldCancelledReason, field.TypeString, value)
		_node.CancelledReason = value
	}
	if value, ok := _c.mutation.ManualOverrideFields(); ok {
		_spec.SetField(event.FieldManualOverrideFields, field.TypeJSON, value)
		_node.ManualOverrideFields = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(event.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(event.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.CategoryTable,
			Columns: []string{event.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventcategory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OccurrencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.OccurrencesTable,
			Columns: []string{event.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.SourceRecordsTable,
			Columns: []string{event.SourceRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsourcerecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ImportItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   event.ImportItemsTable,
			Columns: []string{event.ImportItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventCreate) OnConflict(opts ...sql.ConflictOption) *EventUpsertOne {
	_c.conflict = opts
	return &EventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventCreate) OnConflictColumns(columns ...string) *EventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertOne{
		create: _c,
	}
}

type (
	// EventUpsertOne is the builder for "upsert"-ing
	//  one Event node.
	EventUpsertOne struct {
		create *EventCreate
	}

	// EventUpsert is the "OnConflict" setter.
	EventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsert) SetUpdatedAt(v time.Time) *EventUpsert {
	u.Set(event.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsert) UpdateUpdatedAt() *EventUpsert {
	u.SetExcluded(event.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventUpsert) SetDeletedAt(v time.Time) *EventUpsert {
	u.Set(event.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventUpsert) UpdateDeletedAt() *EventUpsert {
	u.SetExcluded(event.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventUpsert) ClearDeletedAt() *EventUpsert {
	u.SetNull(event.FieldDeletedAt)
	return u
}

// SetCategoryID sets the "category_id" field.
func (u *EventUpsert) SetCategoryID(v int64) *EventUpsert {
	u.Set(event.FieldCategoryID, v)
	return u
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *EventUpsert) UpdateCategoryID() *EventUpsert {
	u.SetExcluded(event.FieldCategoryID)
	return u
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *EventUpsert) ClearCategoryID() *EventUpsert {
	u.SetNull(event.FieldCategoryID)
	return u
}

// SetTitle sets the "title" field.
func (u *EventUpsert) SetTitle(v string) *EventUpsert {
	u.Set(event.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *EventUpsert) UpdateTitle() *EventUpsert {
	u.SetExcluded(event.FieldTitle)
	return u
}

// SetSummary sets the "summary" field.
func (u *EventUpsert) SetSummary(v string) *EventUpsert {
	u.Set(event.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *EventUpsert) UpdateSummary() *EventUpsert {
	u.SetExcluded(event.FieldSummary)
	return u
}

// SetDescriptionMarkdown sets the "description_markdown" field.
func (u *EventUpsert) SetDescriptionMarkdown(v string) *EventUpsert {
	u.Set(event.FieldDescriptionMarkdown, v)
	return u
}

// UpdateDescriptionMarkdown sets the "description_markdown" field to the value that was provided on create.
func (u *EventUpsert) UpdateDescriptionMarkdown() *EventUpsert {
	u.SetExcluded(event.FieldDescriptionMarkdown)
	return u
}

// SetTags sets the "tags" field.
func (u *EventUpsert) SetTags(v []string) *EventUpsert {
	u.Set(event.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *EventUpsert) UpdateTags() *EventUpsert {
	u.SetExcluded(event.FieldTags)
	return u
}

// SetOrganizerName sets the "organizer_name" field.
func (u *EventUpsert) SetOrganizerName(v string) *EventUpsert {
	u.Set(event.FieldOrganizerName, v)
	return u
}

// UpdateOrganizerName sets the "organizer_name" field to the value that was provided on create.
func (u *EventUpsert) UpdateOrganizerName() *EventUpsert {
	u.SetExcluded(event.FieldOrganizerName)
	return u
}

// SetOrganizerURL sets the "organizer_url" field.
func (u *EventUpsert) SetOrganizerURL(v string) *EventUpsert {
	u.Set(event.FieldOrganizerURL, v)
	return u
}

// UpdateOrganizerURL sets the "organizer_url" field to the value that was provided on create.
func (u *EventUpsert) UpdateOrganizerURL() *EventUpsert {
	u.SetExcluded(event.FieldOrganizerURL)
	return u
}

// SetFeeType sets the "fee_type" field.
func (u *EventUpsert) SetFeeType(v string) *EventUpsert {
	u.Set(event.FieldFeeType, v)
	return u
}

// UpdateFeeType sets the "fee_type" field to the value that was provided on create.
func (u *EventUpsert) UpdateFeeType() *EventUpsert {
	u.SetExcluded(event.FieldFeeType)
	return u
}

// SetPriceMin sets the "price_min" field.
func (u *EventUpsert) SetPriceMin(v float64) *EventUpsert {
	u.Set(event.FieldPriceMin, v)
	return u
}

// UpdatePriceMin sets the "price_min" field to the value that was provided on create.
func (u *EventUpsert) UpdatePriceMin() *EventUpsert {
	u.SetExcluded(event.FieldPriceMin)
	return u
}

// AddPriceMin adds v to the "price_min" field.
func (u *EventUpsert) AddPriceMin(v float64) *EventUpsert {
	u.Add(event.FieldPriceMin, v)
	return u
}

// ClearPriceMin clears the value of the "price_min" field.
func (u *EventUpsert) ClearPriceMin() *EventUpsert {
	u.SetNull(event.FieldPriceMin)
	return u
}

// SetPriceMax sets the "price_max" field.
func (u *EventUpsert) SetPriceMax(v float64) *EventUpsert {
	u.Set(event.FieldPriceMax, v)
	return u
}

// UpdatePriceMax sets the "price_max" field to the value that was provided on create.
func (u *EventUpsert) UpdatePriceMax() *EventUpsert {
	u.SetExcluded(event.FieldPriceMax)
	return u
}

// AddPriceMax adds v to the "price_max" field.
func (u *EventUpsert) AddPriceMax(v float64) *EventUpsert {
	u.Add(event.FieldPriceMax, v)
	return u
}

// ClearPriceMax clears the value of the "price_max" field.
func (u *EventUpsert) ClearPriceMax() *EventUpsert {
	u.SetNull(event.FieldPriceMax)
	return u
}

// SetCurrency sets the "currency" field.
func (u *EventUpsert) SetCurrency(v string) *EventUpsert {
	u.Set(event.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *EventUpsert) UpdateCurrency() *EventUpsert {
	u.SetExcluded(event.FieldCurrency)
	return u
}

// SetRegistrationURL sets the "registration_url" field.
func (u *EventUpsert) SetRegistrationURL(v string) *EventUpsert {
	u.Set(event.FieldRegistrationURL, v)
	return u
}

// UpdateRegistrationURL sets the "registration_url" field to the value that was provided on create.
func (u *EventUpsert) UpdateRegistrationURL() *EventUpsert {
	u.SetExcluded(event.FieldRegistrationURL)
	return u
}

// SetRegistrationDeadline sets the "registration_deadline" field.
func (u *EventUpsert) SetRegistrationDeadline(v time.Time) *EventUpsert {
	u.Set(event.FieldRegistrationDeadline, v)
	return u
}

// UpdateRegistrationDeadline sets the "registration_deadline" field to the value that was provided on create.
func (u *EventUpsert) UpdateRegistrationDeadline() *EventUpsert {
	u.SetExcluded(event.FieldRegistrationDeadline)
	return u
}

// ClearRegistrationDeadline clears the value of the "registration_deadline" field.
func (u *EventUpsert) ClearRegistrationDeadline() *EventUpsert {
	u.SetNull(event.FieldRegistrationDeadline)
	return u
}

// SetCoverURL sets the "cover_url" field.
func (u *EventUpsert) SetCoverURL(v string) *EventUpsert {
	u.Set(event.FieldCoverURL, v)
	return u
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *EventUpsert) UpdateCoverURL() *EventUpsert {
	u.SetExcluded(event.FieldCoverURL)
	return u
}

// SetStatus sets the "status" field.
func (u *EventUpsert) SetStatus(v string) *EventUpsert {
	u.Set(event.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EventUpsert) UpdateStatus() *EventUpsert {
	u.SetExcluded(event.FieldStatus)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *EventUpsert) SetVisibility(v string) *EventUpsert {
	u.Set(event.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *EventUpsert) UpdateVisibility() *EventUpsert {
	u.SetExcluded(event.FieldVisibility)
	return u
}

// SetAudience sets the "audience" field.
func (u *EventUpsert) SetAudience(v domain.EventAudience) *EventUpsert {
	u.Set(event.FieldAudience, v)
	return u
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *EventUpsert) UpdateAudience() *EventUpsert {
	u.SetExcluded(event.FieldAudience)
	return u
}

// SetVisibleFrom sets the "visible_from" field.
func (u *EventUpsert) SetVisibleFrom(v time.Time) *EventUpsert {
	u.Set(event.FieldVisibleFrom, v)
	return u
}

// UpdateVisibleFrom sets the "visible_from" field to the value that was provided on create.
func (u *EventUpsert) UpdateVisibleFrom() *EventUpsert {
	u.SetExcluded(event.FieldVisibleFrom)
	return u
}

// ClearVisibleFrom clears the value of the "visible_from" field.
func (u *EventUpsert) ClearVisibleFrom() *EventUpsert {
	u.SetNull(event.FieldVisibleFrom)
	return u
}

// SetVisibleUntil sets the "visible_until" field.
func (u *EventUpsert) SetVisibleUntil(v time.Time) *EventUpsert {
	u.Set(event.FieldVisibleUntil, v)
	return u
}

// UpdateVisibleUntil sets the "visible_until" field to the value that was provided on create.
func (u *EventUpsert) UpdateVisibleUntil() *EventUpsert {
	u.SetExcluded(event.FieldVisibleUntil)
	return u
}

// ClearVisibleUntil clears the value of the "visible_until" field.
func (u *EventUpsert) ClearVisibleUntil() *EventUpsert {
	u.SetNull(event.FieldVisibleUntil)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *EventUpsert) SetPublishedAt(v time.Time) *EventUpsert {
	u.Set(event.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *EventUpsert) UpdatePublishedAt() *EventUpsert {
	u.SetExcluded(event.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *EventUpsert) ClearPublishedAt() *EventUpsert {
	u.SetNull(event.FieldPublishedAt)
	return u
}

// SetCancelledReason sets the "cancelled_reason" field.
func (u *EventUpsert) SetCancelledReason(v string) *EventUpsert {
	u.Set(event.FieldCancelledReason, v)
	return u
}

// UpdateCancelledReason sets the "cancelled_reason" field to the value that was provided on create.
func (u *EventUpsert) UpdateCancelledReason() *EventUpsert {
	u.SetExcluded(event.FieldCancelledReason)
	return u
}

// SetManualOverrideFields sets the "manual_override_fields" field.
func (u *EventUpsert) SetManualOverrideFields(v []string) *EventUpsert {
	u.Set(event.FieldManualOverrideFields, v)
	return u
}

// UpdateManualOverrideFields sets the "manual_override_fields" field to the value that was provided on create.
func (u *EventUpsert) UpdateManualOverrideFields() *EventUpsert {
	u.SetExcluded(event.FieldManualOverrideFields)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *EventUpsert) SetCreatedBy(v int64) *EventUpsert {
	u.Set(event.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *EventUpsert) UpdateCreatedBy() *EventUpsert {
	u.SetExcluded(event.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *EventUpsert) AddCreatedBy(v int64) *EventUpsert {
	u.Add(event.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *EventUpsert) ClearCreatedBy() *EventUpsert {
	u.SetNull(event.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *EventUpsert) SetUpdatedBy(v int64) *EventUpsert {
	u.Set(event.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *EventUpsert) UpdateUpdatedBy() *EventUpsert {
	u.SetExcluded(event.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *EventUpsert) AddUpdatedBy(v int64) *EventUpsert {
	u.Add(event.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *EventUpsert) ClearUpdatedBy() *EventUpsert {
	u.SetNull(event.FieldUpdatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventUpsertOne) UpdateNewValues() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(event.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EventUpsertOne) Ignore() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertOne) DoNothing() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreate.OnConflict
// documentation for more info.
func (u *EventUpsertOne) Update(set func(*EventUpsert)) *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsertOne) SetUpdatedAt(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateUpdatedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventUpsertOne) SetDeletedAt(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateDeletedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventUpsertOne) ClearDeletedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *EventUpsertOne) SetCategoryID(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateCategoryID() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCategoryID()
	})
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *EventUpsertOne) ClearCategoryID() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearCategoryID()
	})
}

// SetTitle sets the "title" field.
func (u *EventUpsertOne) SetTitle(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateTitle() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTitle()
	})
}

// SetSummary sets the "summary" field.
func (u *EventUpsertOne) SetSummary(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateSummary() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateSummary()
	})
}

// SetDescriptionMarkdown sets the "description_markdown" field.
func (u *EventUpsertOne) SetDescriptionMarkdown(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetDescriptionMarkdown(v)
	})
}

// UpdateDescriptionMarkdown sets the "description_markdown" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateDescriptionMarkdown() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDescriptionMarkdown()
	})
}

// SetTags sets the "tags" field.
func (u *EventUpsertOne) SetTags(v []string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateTags() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTags()
	})
}

// SetOrganizerName sets the "organizer_name" field.
func (u *EventUpsertOne) SetOrganizerName(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetOrganizerName(v)
	})
}

// UpdateOrganizerName sets the "organizer_name" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateOrganizerName() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateOrganizerName()
	})
}

// SetOrganizerURL sets the "organizer_url" field.
func (u *EventUpsertOne) SetOrganizerURL(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetOrganizerURL(v)
	})
}

// UpdateOrganizerURL sets the "organizer_url" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateOrganizerURL() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateOrganizerURL()
	})
}

// SetFeeType sets the "fee_type" field.
func (u *EventUpsertOne) SetFeeType(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetFeeType(v)
	})
}

// UpdateFeeType sets the "fee_type" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateFeeType() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateFeeType()
	})
}

// SetPriceMin sets the "price_min" field.
func (u *EventUpsertOne) SetPriceMin(v float64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetPriceMin(v)
	})
}

// AddPriceMin adds v to the "price_min" field.
func (u *EventUpsertOne) AddPriceMin(v float64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddPriceMin(v)
	})
}

// UpdatePriceMin sets the "price_min" field to the value that was provided on create.
func (u *EventUpsertOne) UpdatePriceMin() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePriceMin()
	})
}

// ClearPriceMin clears the value of the "price_min" field.
func (u *EventUpsertOne) ClearPriceMin() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearPriceMin()
	})
}

// SetPriceMax sets the "price_max" field.
func (u *EventUpsertOne) SetPriceMax(v float64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetPriceMax(v)
	})
}

// AddPriceMax adds v to the "price_max" field.
func (u *EventUpsertOne) AddPriceMax(v float64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddPriceMax(v)
	})
}

// UpdatePriceMax sets the "price_max" field to the value that was provided on create.
func (u *EventUpsertOne) UpdatePriceMax() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePriceMax()
	})
}

// ClearPriceMax clears the value of the "price_max" field.
func (u *EventUpsertOne) ClearPriceMax() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearPriceMax()
	})
}

// SetCurrency sets the "currency" field.
func (u *EventUpsertOne) SetCurrency(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateCurrency() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCurrency()
	})
}

// SetRegistrationURL sets the "registration_url" field.
func (u *EventUpsertOne) SetRegistrationURL(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetRegistrationURL(v)
	})
}

// UpdateRegistrationURL sets the "registration_url" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateRegistrationURL() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateRegistrationURL()
	})
}

// SetRegistrationDeadline sets the "registration_deadline" field.
func (u *EventUpsertOne) SetRegistrationDeadline(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetRegistrationDeadline(v)
	})
}

// UpdateRegistrationDeadline sets the "registration_deadline" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateRegistrationDeadline() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateRegistrationDeadline()
	})
}

// ClearRegistrationDeadline clears the value of the "registration_deadline" field.
func (u *EventUpsertOne) ClearRegistrationDeadline() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearRegistrationDeadline()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *EventUpsertOne) SetCoverURL(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateCoverURL() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCoverURL()
	})
}

// SetStatus sets the "status" field.
func (u *EventUpsertOne) SetStatus(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateStatus() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateStatus()
	})
}

// SetVisibility sets the "visibility" field.
func (u *EventUpsertOne) SetVisibility(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateVisibility() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateVisibility()
	})
}

// SetAudience sets the "audience" field.
func (u *EventUpsertOne) SetAudience(v domain.EventAudience) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetAudience(v)
	})
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateAudience() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateAudience()
	})
}

// SetVisibleFrom sets the "visible_from" field.
func (u *EventUpsertOne) SetVisibleFrom(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetVisibleFrom(v)
	})
}

// UpdateVisibleFrom sets the "visible_from" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateVisibleFrom() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateVisibleFrom()
	})
}

// ClearVisibleFrom clears the value of the "visible_from" field.
func (u *EventUpsertOne) ClearVisibleFrom() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearVisibleFrom()
	})
}

// SetVisibleUntil sets the "visible_until" field.
func (u *EventUpsertOne) SetVisibleUntil(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetVisibleUntil(v)
	})
}

// UpdateVisibleUntil sets the "visible_until" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateVisibleUntil() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateVisibleUntil()
	})
}

// ClearVisibleUntil clears the value of the "visible_until" field.
func (u *EventUpsertOne) ClearVisibleUntil() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearVisibleUntil()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *EventUpsertOne) SetPublishedAt(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *EventUpsertOne) UpdatePublishedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *EventUpsertOne) ClearPublishedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearPublishedAt()
	})
}

// SetCancelledReason sets the "cancelled_reason" field.
func (u *EventUpsertOne) SetCancelledReason(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetCancelledReason(v)
	})
}

// UpdateCancelledReason sets the "cancelled_reason" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateCancelledReason() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCancelledReason()
	})
}

// SetManualOverrideFields sets the "manual_override_fields" field.
func (u *EventUpsertOne) SetManualOverrideFields(v []string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetManualOverrideFields(v)
	})
}

// UpdateManualOverrideFields sets the "manual_override_fields" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateManualOverrideFields() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateManualOverrideFields()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *EventUpsertOne) SetCreatedBy(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *EventUpsertOne) AddCreatedBy(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateCreatedBy() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *EventUpsertOne) ClearCreatedBy() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *EventUpsertOne) SetUpdatedBy(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *EventUpsertOne) AddUpdatedBy(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateUpdatedBy() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *EventUpsertOne) ClearUpdatedBy() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *EventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
	conflict []sql.ConflictOption
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventCreateBulk) OnConflict(opts ...sql.ConflictOption) *EventUpsertBulk {
	_c.conflict = opts
	return &EventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventCreateBulk) OnConflictColumns(columns ...string) *EventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertBulk{
		create: _c,
	}
}

// EventUpsertBulk is the builder for "upsert"-ing
// a bulk of Event nodes.
type EventUpsertBulk struct {
	create *EventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventUpsertBulk) UpdateNewValues() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(event.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EventUpsertBulk) Ignore() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertBulk) DoNothing() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreateBulk.OnConflict
// documentation for more info.
func (u *EventUpsertBulk) Update(set func(*EventUpsert)) *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsertBulk) SetUpdatedAt(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateUpdatedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventUpsertBulk) SetDeletedAt(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateDeletedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventUpsertBulk) ClearDeletedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *EventUpsertBulk) SetCategoryID(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateCategoryID() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCategoryID()
	})
}

// ClearCategoryID clears the value of the "category_id" field.
func (u *EventUpsertBulk) ClearCategoryID() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearCategoryID()
	})
}

// SetTitle sets the "title" field.
func (u *EventUpsertBulk) SetTitle(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateTitle() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTitle()
	})
}

// SetSummary sets the "summary" field.
func (u *EventUpsertBulk) SetSummary(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateSummary() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateSummary()
	})
}

// SetDescriptionMarkdown sets the "description_markdown" field.
func (u *EventUpsertBulk) SetDescriptionMarkdown(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetDescriptionMarkdown(v)
	})
}

// UpdateDescriptionMarkdown sets the "description_markdown" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateDescriptionMarkdown() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDescriptionMarkdown()
	})
}

// SetTags sets the "tags" field.
func (u *EventUpsertBulk) SetTags(v []string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateTags() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTags()
	})
}

// SetOrganizerName sets the "organizer_name" field.
func (u *EventUpsertBulk) SetOrganizerName(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetOrganizerName(v)
	})
}

// UpdateOrganizerName sets the "organizer_name" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateOrganizerName() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateOrganizerName()
	})
}

// SetOrganizerURL sets the "organizer_url" field.
func (u *EventUpsertBulk) SetOrganizerURL(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetOrganizerURL(v)
	})
}

// UpdateOrganizerURL sets the "organizer_url" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateOrganizerURL() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateOrganizerURL()
	})
}

// SetFeeType sets the "fee_type" field.
func (u *EventUpsertBulk) SetFeeType(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetFeeType(v)
	})
}

// UpdateFeeType sets the "fee_type" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateFeeType() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateFeeType()
	})
}

// SetPriceMin sets the "price_min" field.
func (u *EventUpsertBulk) SetPriceMin(v float64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetPriceMin(v)
	})
}

// AddPriceMin adds v to the "price_min" field.
func (u *EventUpsertBulk) AddPriceMin(v float64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddPriceMin(v)
	})
}

// UpdatePriceMin sets the "price_min" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdatePriceMin() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePriceMin()
	})
}

// ClearPriceMin clears the value of the "price_min" field.
func (u *EventUpsertBulk) ClearPriceMin() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearPriceMin()
	})
}

// SetPriceMax sets the "price_max" field.
func (u *EventUpsertBulk) SetPriceMax(v float64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetPriceMax(v)
	})
}

// AddPriceMax adds v to the "price_max" field.
func (u *EventUpsertBulk) AddPriceMax(v float64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddPriceMax(v)
	})
}

// UpdatePriceMax sets the "price_max" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdatePriceMax() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePriceMax()
	})
}

// ClearPriceMax clears the value of the "price_max" field.
func (u *EventUpsertBulk) ClearPriceMax() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearPriceMax()
	})
}

// SetCurrency sets the "currency" field.
func (u *EventUpsertBulk) SetCurrency(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateCurrency() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCurrency()
	})
}

// SetRegistrationURL sets the "registration_url" field.
func (u *EventUpsertBulk) SetRegistrationURL(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetRegistrationURL(v)
	})
}

// UpdateRegistrationURL sets the "registration_url" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateRegistrationURL() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateRegistrationURL()
	})
}

// SetRegistrationDeadline sets the "registration_deadline" field.
func (u *EventUpsertBulk) SetRegistrationDeadline(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetRegistrationDeadline(v)
	})
}

// UpdateRegistrationDeadline sets the "registration_deadline" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateRegistrationDeadline() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateRegistrationDeadline()
	})
}

// ClearRegistrationDeadline clears the value of the "registration_deadline" field.
func (u *EventUpsertBulk) ClearRegistrationDeadline() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearRegistrationDeadline()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *EventUpsertBulk) SetCoverURL(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateCoverURL() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCoverURL()
	})
}

// SetStatus sets the "status" field.
func (u *EventUpsertBulk) SetStatus(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateStatus() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateStatus()
	})
}

// SetVisibility sets the "visibility" field.
func (u *EventUpsertBulk) SetVisibility(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateVisibility() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateVisibility()
	})
}

// SetAudience sets the "audience" field.
func (u *EventUpsertBulk) SetAudience(v domain.EventAudience) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetAudience(v)
	})
}

// UpdateAudience sets the "audience" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateAudience() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateAudience()
	})
}

// SetVisibleFrom sets the "visible_from" field.
func (u *EventUpsertBulk) SetVisibleFrom(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetVisibleFrom(v)
	})
}

// UpdateVisibleFrom sets the "visible_from" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateVisibleFrom() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateVisibleFrom()
	})
}

// ClearVisibleFrom clears the value of the "visible_from" field.
func (u *EventUpsertBulk) ClearVisibleFrom() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearVisibleFrom()
	})
}

// SetVisibleUntil sets the "visible_until" field.
func (u *EventUpsertBulk) SetVisibleUntil(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetVisibleUntil(v)
	})
}

// UpdateVisibleUntil sets the "visible_until" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateVisibleUntil() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateVisibleUntil()
	})
}

// ClearVisibleUntil clears the value of the "visible_until" field.
func (u *EventUpsertBulk) ClearVisibleUntil() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearVisibleUntil()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *EventUpsertBulk) SetPublishedAt(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdatePublishedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *EventUpsertBulk) ClearPublishedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearPublishedAt()
	})
}

// SetCancelledReason sets the "cancelled_reason" field.
func (u *EventUpsertBulk) SetCancelledReason(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetCancelledReason(v)
	})
}

// UpdateCancelledReason sets the "cancelled_reason" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateCancelledReason() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCancelledReason()
	})
}

// SetManualOverrideFields sets the "manual_override_fields" field.
func (u *EventUpsertBulk) SetManualOverrideFields(v []string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetManualOverrideFields(v)
	})
}

// UpdateManualOverrideFields sets the "manual_override_fields" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateManualOverrideFields() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateManualOverrideFields()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *EventUpsertBulk) SetCreatedBy(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *EventUpsertBulk) AddCreatedBy(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateCreatedBy() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *EventUpsertBulk) ClearCreatedBy() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *EventUpsertBulk) SetUpdatedBy(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *EventUpsertBulk) AddUpdatedBy(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateUpdatedBy() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *EventUpsertBulk) ClearUpdatedBy() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *EventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
