// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/eventimportbatch"
	"github.com/Wei-Shaw/sub2api/ent/eventimportitem"
	"github.com/Wei-Shaw/sub2api/ent/eventsource"
)

// EventImportBatchCreate is the builder for creating a EventImportBatch entity.
type EventImportBatchCreate struct {
	config
	mutation *EventImportBatchMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventImportBatchCreate) SetCreatedAt(v time.Time) *EventImportBatchCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableCreatedAt(v *time.Time) *EventImportBatchCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventImportBatchCreate) SetUpdatedAt(v time.Time) *EventImportBatchCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableUpdatedAt(v *time.Time) *EventImportBatchCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *EventImportBatchCreate) SetSourceID(v int64) *EventImportBatchCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *EventImportBatchCreate) SetFileName(v string) *EventImportBatchCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableFileName(v *string) *EventImportBatchCreate {
	if v != nil {
		_c.SetFileName(*v)
	}
	return _c
}

// SetFileHash sets the "file_hash" field.
func (_c *EventImportBatchCreate) SetFileHash(v string) *EventImportBatchCreate {
	_c.mutation.SetFileHash(v)
	return _c
}

// SetSchemaVersion sets the "schema_version" field.
func (_c *EventImportBatchCreate) SetSchemaVersion(v int) *EventImportBatchCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *EventImportBatchCreate) SetMode(v string) *EventImportBatchCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableMode(v *string) *EventImportBatchCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EventImportBatchCreate) SetStatus(v string) *EventImportBatchCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableStatus(v *string) *EventImportBatchCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalCount sets the "total_count" field.
func (_c *EventImportBatchCreate) SetTotalCount(v int) *EventImportBatchCreate {
	_c.mutation.SetTotalCount(v)
	return _c
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableTotalCount(v *int) *EventImportBatchCreate {
	if v != nil {
		_c.SetTotalCount(*v)
	}
	return _c
}

// SetCreateCount sets the "create_count" field.
func (_c *EventImportBatchCreate) SetCreateCount(v int) *EventImportBatchCreate {
	_c.mutation.SetCreateCount(v)
	return _c
}

// SetNillableCreateCount sets the "create_count" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableCreateCount(v *int) *EventImportBatchCreate {
	if v != nil {
		_c.SetCreateCount(*v)
	}
	return _c
}

// SetUpdateCount sets the "update_count" field.
func (_c *EventImportBatchCreate) SetUpdateCount(v int) *EventImportBatchCreate {
	_c.mutation.SetUpdateCount(v)
	return _c
}

// SetNillableUpdateCount sets the "update_count" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableUpdateCount(v *int) *EventImportBatchCreate {
	if v != nil {
		_c.SetUpdateCount(*v)
	}
	return _c
}

// SetUnchangedCount sets the "unchanged_count" field.
func (_c *EventImportBatchCreate) SetUnchangedCount(v int) *EventImportBatchCreate {
	_c.mutation.SetUnchangedCount(v)
	return _c
}

// SetNillableUnchangedCount sets the "unchanged_count" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableUnchangedCount(v *int) *EventImportBatchCreate {
	if v != nil {
		_c.SetUnchangedCount(*v)
	}
	return _c
}

// SetConflictCount sets the "conflict_count" field.
func (_c *EventImportBatchCreate) SetConflictCount(v int) *EventImportBatchCreate {
	_c.mutation.SetConflictCount(v)
	return _c
}

// SetNillableConflictCount sets the "conflict_count" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableConflictCount(v *int) *EventImportBatchCreate {
	if v != nil {
		_c.SetConflictCount(*v)
	}
	return _c
}

// SetErrorCount sets the "error_count" field.
func (_c *EventImportBatchCreate) SetErrorCount(v int) *EventImportBatchCreate {
	_c.mutation.SetErrorCount(v)
	return _c
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableErrorCount(v *int) *EventImportBatchCreate {
	if v != nil {
		_c.SetErrorCount(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EventImportBatchCreate) SetCreatedBy(v int64) *EventImportBatchCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCommittedAt sets the "committed_at" field.
func (_c *EventImportBatchCreate) SetCommittedAt(v time.Time) *EventImportBatchCreate {
	_c.mutation.SetCommittedAt(v)
	return _c
}

// SetNillableCommittedAt sets the "committed_at" field if the given value is not nil.
func (_c *EventImportBatchCreate) SetNillableCommittedAt(v *time.Time) *EventImportBatchCreate {
	if v != nil {
		_c.SetCommittedAt(*v)
	}
	return _c
}

// SetSource sets the "source" edge to the EventSource entity.
func (_c *EventImportBatchCreate) SetSource(v *EventSource) *EventImportBatchCreate {
	return _c.SetSourceID(v.ID)
}

// AddItemIDs adds the "items" edge to the EventImportItem entity by IDs.
func (_c *EventImportBatchCreate) AddItemIDs(ids ...int64) *EventImportBatchCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the EventImportItem entity.
func (_c *EventImportBatchCreate) AddItems(v ...*EventImportItem) *EventImportBatchCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the EventImportBatchMutation object of the builder.
func (_c *EventImportBatchCreate) Mutation() *EventImportBatchMutation {
	return _c.mutation
}

// Save creates the EventImportBatch in the database.
func (_c *EventImportBatchCreate) Save(ctx context.Context) (*EventImportBatch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventImportBatchCreate) SaveX(ctx context.Context) *EventImportBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventImportBatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventImportBatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventImportBatchCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := eventimportbatch.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := eventimportbatch.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FileName(); !ok {
		v := eventimportbatch.DefaultFileName
		_c.mutation.SetFileName(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := eventimportbatch.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := eventimportbatch.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalCount(); !ok {
		v := eventimportbatch.DefaultTotalCount
		_c.mutation.SetTotalCount(v)
	}
	if _, ok := _c.mutation.CreateCount(); !ok {
		v := eventimportbatch.DefaultCreateCount
		_c.mutation.SetCreateCount(v)
	}
	if _, ok := _c.mutation.UpdateCount(); !ok {
		v := eventimportbatch.DefaultUpdateCount
		_c.mutation.SetUpdateCount(v)
	}
	if _, ok := _c.mutation.UnchangedCount(); !ok {
		v := eventimportbatch.DefaultUnchangedCount
		_c.mutation.SetUnchangedCount(v)
	}
	if _, ok := _c.mutation.ConflictCount(); !ok {
		v := eventimportbatch.DefaultConflictCount
		_c.mutation.SetConflictCount(v)
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		v := eventimportbatch.DefaultErrorCount
		_c.mutation.SetErrorCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventImportBatchCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventImportBatch.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventImportBatch.updated_at"`)}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "EventImportBatch.source_id"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "EventImportBatch.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := eventimportbatch.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "EventImportBatch.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileHash(); !ok {
		return &ValidationError{Name: "file_hash", err: errors.New(`ent: missing required field "EventImportBatch.file_hash"`)}
	}
	if v, ok := _c.mutation.FileHash(); ok {
		if err := eventimportbatch.FileHashValidator(v); err != nil {
			return &ValidationError{Name: "file_hash", err: fmt.Errorf(`ent: validator failed for field "EventImportBatch.file_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schema_version", err: errors.New(`ent: missing required field "EventImportBatch.schema_version"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "EventImportBatch.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := eventimportbatch.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "EventImportBatch.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EventImportBatch.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := eventimportbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EventImportBatch.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalCount(); !ok {
		return &ValidationError{Name: "total_count", err: errors.New(`ent: missing required field "EventImportBatch.total_count"`)}
	}
	if _, ok := _c.mutation.CreateCount(); !ok {
		return &ValidationError{Name: "create_count", err: errors.New(`ent: missing required field "EventImportBatch.create_count"`)}
	}
	if _, ok := _c.mutation.UpdateCount(); !ok {
		return &ValidationError{Name: "update_count", err: errors.New(`ent: missing required field "EventImportBatch.update_count"`)}
	}
	if _, ok := _c.mutation.UnchangedCount(); !ok {
		return &ValidationError{Name: "unchanged_count", err: errors.New(`ent: missing required field "EventImportBatch.unchanged_count"`)}
	}
	if _, ok := _c.mutation.ConflictCount(); !ok {
		return &ValidationError{Name: "conflict_count", err: errors.New(`ent: missing required field "EventImportBatch.conflict_count"`)}
	}
	if _, ok := _c.mutation.ErrorCount(); !ok {
		return &ValidationError{Name: "error_count", err: errors.New(`ent: missing required field "EventImportBatch.error_count"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "EventImportBatch.created_by"`)}
	}
	if len(_c.mutation.SourceIDs()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required edge "EventImportBatch.source"`)}
	}
	return nil
}

func (_c *EventImportBatchCreate) sqlSave(ctx context.Context) (*EventImportBatch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventImportBatchCreate) createSpec() (*EventImportBatch, *sqlgraph.CreateSpec) {
	var (
		_node = &EventImportBatch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventimportbatch.Table, sqlgraph.NewFieldSpec(eventimportbatch.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(eventimportbatch.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(eventimportbatch.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(eventimportbatch.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.FileHash(); ok {
		_spec.SetField(eventimportbatch.FieldFileHash, field.TypeString, value)
		_node.FileHash = value
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(eventimportbatch.FieldSchemaVersion, field.TypeInt, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(eventimportbatch.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(eventimportbatch.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalCount(); ok {
		_spec.SetField(eventimportbatch.FieldTotalCount, field.TypeInt, value)
		_node.TotalCount = value
	}
	if value, ok := _c.mutation.CreateCount(); ok {
		_spec.SetField(eventimportbatch.FieldCreateCount, field.TypeInt, value)
		_node.CreateCount = value
	}
	if value, ok := _c.mutation.UpdateCount(); ok {
		_spec.SetField(eventimportbatch.FieldUpdateCount, field.TypeInt, value)
		_node.UpdateCount = value
	}
	if value, ok := _c.mutation.UnchangedCount(); ok {
		_spec.SetField(eventimportbatch.FieldUnchangedCount, field.TypeInt, value)
		_node.UnchangedCount = value
	}
	if value, ok := _c.mutation.ConflictCount(); ok {
		_spec.SetField(eventimportbatch.FieldConflictCount, field.TypeInt, value)
		_node.ConflictCount = value
	}
	if value, ok := _c.mutation.ErrorCount(); ok {
		_spec.SetField(eventimportbatch.FieldErrorCount, field.TypeInt, value)
		_node.ErrorCount = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(eventimportbatch.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CommittedAt(); ok {
		_spec.SetField(eventimportbatch.FieldCommittedAt, field.TypeTime, value)
		_node.CommittedAt = &value
	}
	if nodes := _c.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventimportbatch.SourceTable,
			Columns: []string{eventimportbatch.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventsource.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   eventimportbatch.ItemsTable,
			Columns: []string{eventimportbatch.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventimportitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EventImportBatch.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventImportBatchUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventImportBatchCreate) OnConflict(opts ...sql.ConflictOption) *EventImportBatchUpsertOne {
	_c.conflict = opts
	return &EventImportBatchUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EventImportBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventImportBatchCreate) OnConflictColumns(columns ...string) *EventImportBatchUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventImportBatchUpsertOne{
		create: _c,
	}
}

type (
	// EventImportBatchUpsertOne is the builder for "upsert"-ing
	//  one EventImportBatch node.
	EventImportBatchUpsertOne struct {
		create *EventImportBatchCreate
	}

	// EventImportBatchUpsert is the "OnConflict" setter.
	EventImportBatchUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EventImportBatchUpsert) SetUpdatedAt(v time.Time) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateUpdatedAt() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldUpdatedAt)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *EventImportBatchUpsert) SetSourceID(v int64) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateSourceID() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldSourceID)
	return u
}

// SetFileName sets the "file_name" field.
func (u *EventImportBatchUpsert) SetFileName(v string) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateFileName() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldFileName)
	return u
}

// SetFileHash sets the "file_hash" field.
func (u *EventImportBatchUpsert) SetFileHash(v string) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldFileHash, v)
	return u
}

// UpdateFileHash sets the "file_hash" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateFileHash() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldFileHash)
	return u
}

// SetSchemaVersion sets the "schema_version" field.
func (u *EventImportBatchUpsert) SetSchemaVersion(v int) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldSchemaVersion, v)
	return u
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateSchemaVersion() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldSchemaVersion)
	return u
}

// AddSchemaVersion adds v to the "schema_version" field.
func (u *EventImportBatchUpsert) AddSchemaVersion(v int) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldSchemaVersion, v)
	return u
}

// SetMode sets the "mode" field.
func (u *EventImportBatchUpsert) SetMode(v string) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateMode() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldMode)
	return u
}

// SetStatus sets the "status" field.
func (u *EventImportBatchUpsert) SetStatus(v string) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateStatus() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldStatus)
	return u
}

// SetTotalCount sets the "total_count" field.
func (u *EventImportBatchUpsert) SetTotalCount(v int) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldTotalCount, v)
	return u
}

// UpdateTotalCount sets the "total_count" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateTotalCount() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldTotalCount)
	return u
}

// AddTotalCount adds v to the "total_count" field.
func (u *EventImportBatchUpsert) AddTotalCount(v int) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldTotalCount, v)
	return u
}

// SetCreateCount sets the "create_count" field.
func (u *EventImportBatchUpsert) SetCreateCount(v int) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldCreateCount, v)
	return u
}

// UpdateCreateCount sets the "create_count" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateCreateCount() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldCreateCount)
	return u
}

// AddCreateCount adds v to the "create_count" field.
func (u *EventImportBatchUpsert) AddCreateCount(v int) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldCreateCount, v)
	return u
}

// SetUpdateCount sets the "update_count" field.
func (u *EventImportBatchUpsert) SetUpdateCount(v int) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldUpdateCount, v)
	return u
}

// UpdateUpdateCount sets the "update_count" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateUpdateCount() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldUpdateCount)
	return u
}

// AddUpdateCount adds v to the "update_count" field.
func (u *EventImportBatchUpsert) AddUpdateCount(v int) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldUpdateCount, v)
	return u
}

// SetUnchangedCount sets the "unchanged_count" field.
func (u *EventImportBatchUpsert) SetUnchangedCount(v int) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldUnchangedCount, v)
	return u
}

// UpdateUnchangedCount sets the "unchanged_count" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateUnchangedCount() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldUnchangedCount)
	return u
}

// AddUnchangedCount adds v to the "unchanged_count" field.
func (u *EventImportBatchUpsert) AddUnchangedCount(v int) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldUnchangedCount, v)
	return u
}

// SetConflictCount sets the "conflict_count" field.
func (u *EventImportBatchUpsert) SetConflictCount(v int) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldConflictCount, v)
	return u
}

// UpdateConflictCount sets the "conflict_count" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateConflictCount() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldConflictCount)
	return u
}

// AddConflictCount adds v to the "conflict_count" field.
func (u *EventImportBatchUpsert) AddConflictCount(v int) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldConflictCount, v)
	return u
}

// SetErrorCount sets the "error_count" field.
func (u *EventImportBatchUpsert) SetErrorCount(v int) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldErrorCount, v)
	return u
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateErrorCount() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldErrorCount)
	return u
}

// AddErrorCount adds v to the "error_count" field.
func (u *EventImportBatchUpsert) AddErrorCount(v int) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldErrorCount, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *EventImportBatchUpsert) SetCreatedBy(v int64) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateCreatedBy() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *EventImportBatchUpsert) AddCreatedBy(v int64) *EventImportBatchUpsert {
	u.Add(eventimportbatch.FieldCreatedBy, v)
	return u
}

// SetCommittedAt sets the "committed_at" field.
func (u *EventImportBatchUpsert) SetCommittedAt(v time.Time) *EventImportBatchUpsert {
	u.Set(eventimportbatch.FieldCommittedAt, v)
	return u
}

// UpdateCommittedAt sets the "committed_at" field to the value that was provided on create.
func (u *EventImportBatchUpsert) UpdateCommittedAt() *EventImportBatchUpsert {
	u.SetExcluded(eventimportbatch.FieldCommittedAt)
	return u
}

// ClearCommittedAt clears the value of the "committed_at" field.
func (u *EventImportBatchUpsert) ClearCommittedAt() *EventImportBatchUpsert {
	u.SetNull(eventimportbatch.FieldCommittedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EventImportBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventImportBatchUpsertOne) UpdateNewValues() *EventImportBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(eventimportbatch.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EventImportBatch.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EventImportBatchUpsertOne) Ignore() *EventImportBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventImportBatchUpsertOne) DoNothing() *EventImportBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventImportBatchCreate.OnConflict
// documentation for more info.
func (u *EventImportBatchUpsertOne) Update(set func(*EventImportBatchUpsert)) *EventImportBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventImportBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventImportBatchUpsertOne) SetUpdatedAt(v time.Time) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateUpdatedAt() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSourceID sets the "source_id" field.
func (u *EventImportBatchUpsertOne) SetSourceID(v int64) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateSourceID() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateSourceID()
	})
}

// SetFileName sets the "file_name" field.
func (u *EventImportBatchUpsertOne) SetFileName(v string) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateFileName() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateFileName()
	})
}

// SetFileHash sets the "file_hash" field.
func (u *EventImportBatchUpsertOne) SetFileHash(v string) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetFileHash(v)
	})
}

// UpdateFileHash sets the "file_hash" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateFileHash() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateFileHash()
	})
}

// SetSchemaVersion sets the "schema_version" field.
func (u *EventImportBatchUpsertOne) SetSchemaVersion(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetSchemaVersion(v)
	})
}

// AddSchemaVersion adds v to the "schema_version" field.
func (u *EventImportBatchUpsertOne) AddSchemaVersion(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateSchemaVersion() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetMode sets the "mode" field.
func (u *EventImportBatchUpsertOne) SetMode(v string) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateMode() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateMode()
	})
}

// SetStatus sets the "status" field.
func (u *EventImportBatchUpsertOne) SetStatus(v string) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateStatus() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalCount sets the "total_count" field.
func (u *EventImportBatchUpsertOne) SetTotalCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetTotalCount(v)
	})
}

// AddTotalCount adds v to the "total_count" field.
func (u *EventImportBatchUpsertOne) AddTotalCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddTotalCount(v)
	})
}

// UpdateTotalCount sets the "total_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateTotalCount() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateTotalCount()
	})
}

// SetCreateCount sets the "create_count" field.
func (u *EventImportBatchUpsertOne) SetCreateCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetCreateCount(v)
	})
}

// AddCreateCount adds v to the "create_count" field.
func (u *EventImportBatchUpsertOne) AddCreateCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddCreateCount(v)
	})
}

// UpdateCreateCount sets the "create_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateCreateCount() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateCreateCount()
	})
}

// SetUpdateCount sets the "update_count" field.
func (u *EventImportBatchUpsertOne) SetUpdateCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetUpdateCount(v)
	})
}

// AddUpdateCount adds v to the "update_count" field.
func (u *EventImportBatchUpsertOne) AddUpdateCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddUpdateCount(v)
	})
}

// UpdateUpdateCount sets the "update_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateUpdateCount() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateUpdateCount()
	})
}

// SetUnchangedCount sets the "unchanged_count" field.
func (u *EventImportBatchUpsertOne) SetUnchangedCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetUnchangedCount(v)
	})
}

// AddUnchangedCount adds v to the "unchanged_count" field.
func (u *EventImportBatchUpsertOne) AddUnchangedCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddUnchangedCount(v)
	})
}

// UpdateUnchangedCount sets the "unchanged_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateUnchangedCount() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateUnchangedCount()
	})
}

// SetConflictCount sets the "conflict_count" field.
func (u *EventImportBatchUpsertOne) SetConflictCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetConflictCount(v)
	})
}

// AddConflictCount adds v to the "conflict_count" field.
func (u *EventImportBatchUpsertOne) AddConflictCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddConflictCount(v)
	})
}

// UpdateConflictCount sets the "conflict_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateConflictCount() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateConflictCount()
	})
}

// SetErrorCount sets the "error_count" field.
func (u *EventImportBatchUpsertOne) SetErrorCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetErrorCount(v)
	})
}

// AddErrorCount adds v to the "error_count" field.
func (u *EventImportBatchUpsertOne) AddErrorCount(v int) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddErrorCount(v)
	})
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateErrorCount() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateErrorCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *EventImportBatchUpsertOne) SetCreatedBy(v int64) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *EventImportBatchUpsertOne) AddCreatedBy(v int64) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateCreatedBy() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCommittedAt sets the "committed_at" field.
func (u *EventImportBatchUpsertOne) SetCommittedAt(v time.Time) *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetCommittedAt(v)
	})
}

// UpdateCommittedAt sets the "committed_at" field to the value that was provided on create.
func (u *EventImportBatchUpsertOne) UpdateCommittedAt() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateCommittedAt()
	})
}

// ClearCommittedAt clears the value of the "committed_at" field.
func (u *EventImportBatchUpsertOne) ClearCommittedAt() *EventImportBatchUpsertOne {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.ClearCommittedAt()
	})
}

// Exec executes the query.
func (u *EventImportBatchUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventImportBatchCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventImportBatchUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EventImportBatchUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EventImportBatchUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EventImportBatchCreateBulk is the builder for creating many EventImportBatch entities in bulk.
type EventImportBatchCreateBulk struct {
	config
	err      error
	builders []*EventImportBatchCreate
	conflict []sql.ConflictOption
}

// Save creates the EventImportBatch entities in the database.
func (_c *EventImportBatchCreateBulk) Save(ctx context.Context) ([]*EventImportBatch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventImportBatch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventImportBatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventImportBatchCreateBulk) SaveX(ctx context.Context) []*EventImportBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventImportBatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventImportBatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EventImportBatch.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventImportBatchUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventImportBatchCreateBulk) OnConflict(opts ...sql.ConflictOption) *EventImportBatchUpsertBulk {
	_c.conflict = opts
	return &EventImportBatchUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EventImportBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventImportBatchCreateBulk) OnConflictColumns(columns ...string) *EventImportBatchUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventImportBatchUpsertBulk{
		create: _c,
	}
}

// EventImportBatchUpsertBulk is the builder for "upsert"-ing
// a bulk of EventImportBatch nodes.
type EventImportBatchUpsertBulk struct {
	create *EventImportBatchCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EventImportBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventImportBatchUpsertBulk) UpdateNewValues() *EventImportBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(eventimportbatch.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EventImportBatch.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EventImportBatchUpsertBulk) Ignore() *EventImportBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventImportBatchUpsertBulk) DoNothing() *EventImportBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventImportBatchCreateBulk.OnConflict
// documentation for more info.
func (u *EventImportBatchUpsertBulk) Update(set func(*EventImportBatchUpsert)) *EventImportBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventImportBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventImportBatchUpsertBulk) SetUpdatedAt(v time.Time) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateUpdatedAt() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSourceID sets the "source_id" field.
func (u *EventImportBatchUpsertBulk) SetSourceID(v int64) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateSourceID() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateSourceID()
	})
}

// SetFileName sets the "file_name" field.
func (u *EventImportBatchUpsertBulk) SetFileName(v string) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateFileName() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateFileName()
	})
}

// SetFileHash sets the "file_hash" field.
func (u *EventImportBatchUpsertBulk) SetFileHash(v string) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetFileHash(v)
	})
}

// UpdateFileHash sets the "file_hash" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateFileHash() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateFileHash()
	})
}

// SetSchemaVersion sets the "schema_version" field.
func (u *EventImportBatchUpsertBulk) SetSchemaVersion(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetSchemaVersion(v)
	})
}

// AddSchemaVersion adds v to the "schema_version" field.
func (u *EventImportBatchUpsertBulk) AddSchemaVersion(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schema_version" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateSchemaVersion() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetMode sets the "mode" field.
func (u *EventImportBatchUpsertBulk) SetMode(v string) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateMode() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateMode()
	})
}

// SetStatus sets the "status" field.
func (u *EventImportBatchUpsertBulk) SetStatus(v string) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateStatus() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetTotalCount sets the "total_count" field.
func (u *EventImportBatchUpsertBulk) SetTotalCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetTotalCount(v)
	})
}

// AddTotalCount adds v to the "total_count" field.
func (u *EventImportBatchUpsertBulk) AddTotalCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddTotalCount(v)
	})
}

// UpdateTotalCount sets the "total_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateTotalCount() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateTotalCount()
	})
}

// SetCreateCount sets the "create_count" field.
func (u *EventImportBatchUpsertBulk) SetCreateCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetCreateCount(v)
	})
}

// AddCreateCount adds v to the "create_count" field.
func (u *EventImportBatchUpsertBulk) AddCreateCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddCreateCount(v)
	})
}

// UpdateCreateCount sets the "create_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateCreateCount() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateCreateCount()
	})
}

// SetUpdateCount sets the "update_count" field.
func (u *EventImportBatchUpsertBulk) SetUpdateCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetUpdateCount(v)
	})
}

// AddUpdateCount adds v to the "update_count" field.
func (u *EventImportBatchUpsertBulk) AddUpdateCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddUpdateCount(v)
	})
}

// UpdateUpdateCount sets the "update_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateUpdateCount() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateUpdateCount()
	})
}

// SetUnchangedCount sets the "unchanged_count" field.
func (u *EventImportBatchUpsertBulk) SetUnchangedCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetUnchangedCount(v)
	})
}

// AddUnchangedCount adds v to the "unchanged_count" field.
func (u *EventImportBatchUpsertBulk) AddUnchangedCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddUnchangedCount(v)
	})
}

// UpdateUnchangedCount sets the "unchanged_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateUnchangedCount() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateUnchangedCount()
	})
}

// SetConflictCount sets the "conflict_count" field.
func (u *EventImportBatchUpsertBulk) SetConflictCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetConflictCount(v)
	})
}

// AddConflictCount adds v to the "conflict_count" field.
func (u *EventImportBatchUpsertBulk) AddConflictCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddConflictCount(v)
	})
}

// UpdateConflictCount sets the "conflict_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateConflictCount() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateConflictCount()
	})
}

// SetErrorCount sets the "error_count" field.
func (u *EventImportBatchUpsertBulk) SetErrorCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetErrorCount(v)
	})
}

// AddErrorCount adds v to the "error_count" field.
func (u *EventImportBatchUpsertBulk) AddErrorCount(v int) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddErrorCount(v)
	})
}

// UpdateErrorCount sets the "error_count" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateErrorCount() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateErrorCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *EventImportBatchUpsertBulk) SetCreatedBy(v int64) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *EventImportBatchUpsertBulk) AddCreatedBy(v int64) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateCreatedBy() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetCommittedAt sets the "committed_at" field.
func (u *EventImportBatchUpsertBulk) SetCommittedAt(v time.Time) *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.SetCommittedAt(v)
	})
}

// UpdateCommittedAt sets the "committed_at" field to the value that was provided on create.
func (u *EventImportBatchUpsertBulk) UpdateCommittedAt() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.UpdateCommittedAt()
	})
}

// ClearCommittedAt clears the value of the "committed_at" field.
func (u *EventImportBatchUpsertBulk) ClearCommittedAt() *EventImportBatchUpsertBulk {
	return u.Update(func(s *EventImportBatchUpsert) {
		s.ClearCommittedAt()
	})
}

// Exec executes the query.
func (u *EventImportBatchUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EventImportBatchCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventImportBatchCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventImportBatchUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
