// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/event"
	"github.com/Wei-Shaw/sub2api/ent/eventoccurrence"
)

// EventOccurrenceCreate is the builder for creating a EventOccurrence entity.
type EventOccurrenceCreate struct {
	config
	mutation *EventOccurrenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventOccurrenceCreate) SetCreatedAt(v time.Time) *EventOccurrenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableCreatedAt(v *time.Time) *EventOccurrenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventOccurrenceCreate) SetUpdatedAt(v time.Time) *EventOccurrenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableUpdatedAt(v *time.Time) *EventOccurrenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *EventOccurrenceCreate) SetEventID(v int64) *EventOccurrenceCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *EventOccurrenceCreate) SetStartsAt(v time.Time) *EventOccurrenceCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *EventOccurrenceCreate) SetEndsAt(v time.Time) *EventOccurrenceCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableEndsAt(v *time.Time) *EventOccurrenceCreate {
	if v != nil {
		_c.SetEndsAt(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *EventOccurrenceCreate) SetTimezone(v string) *EventOccurrenceCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableTimezone(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetAllDay sets the "all_day" field.
func (_c *EventOccurrenceCreate) SetAllDay(v bool) *EventOccurrenceCreate {
	_c.mutation.SetAllDay(v)
	return _c
}

// SetNillableAllDay sets the "all_day" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableAllDay(v *bool) *EventOccurrenceCreate {
	if v != nil {
		_c.SetAllDay(*v)
	}
	return _c
}

// SetLocationMode sets the "location_mode" field.
func (_c *EventOccurrenceCreate) SetLocationMode(v string) *EventOccurrenceCreate {
	_c.mutation.SetLocationMode(v)
	return _c
}

// SetNillableLocationMode sets the "location_mode" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableLocationMode(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetLocationMode(*v)
	}
	return _c
}

// SetOnlineURL sets the "online_url" field.
func (_c *EventOccurrenceCreate) SetOnlineURL(v string) *EventOccurrenceCreate {
	_c.mutation.SetOnlineURL(v)
	return _c
}

// SetNillableOnlineURL sets the "online_url" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableOnlineURL(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetOnlineURL(*v)
	}
	return _c
}

// SetVenueName sets the "venue_name" field.
func (_c *EventOccurrenceCreate) SetVenueName(v string) *EventOccurrenceCreate {
	_c.mutation.SetVenueName(v)
	return _c
}

// SetNillableVenueName sets the "venue_name" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableVenueName(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetVenueName(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *EventOccurrenceCreate) SetAddress(v string) *EventOccurrenceCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableAddress(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *EventOccurrenceCreate) SetCountry(v string) *EventOccurrenceCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableCountry(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetProvince sets the "province" field.
func (_c *EventOccurrenceCreate) SetProvince(v string) *EventOccurrenceCreate {
	_c.mutation.SetProvince(v)
	return _c
}

// SetNillableProvince sets the "province" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableProvince(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetProvince(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *EventOccurrenceCreate) SetCity(v string) *EventOccurrenceCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableCity(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetDistrict sets the "district" field.
func (_c *EventOccurrenceCreate) SetDistrict(v string) *EventOccurrenceCreate {
	_c.mutation.SetDistrict(v)
	return _c
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableDistrict(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetDistrict(*v)
	}
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *EventOccurrenceCreate) SetLatitude(v float64) *EventOccurrenceCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableLatitude(v *float64) *EventOccurrenceCreate {
	if v != nil {
		_c.SetLatitude(*v)
	}
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *EventOccurrenceCreate) SetLongitude(v float64) *EventOccurrenceCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableLongitude(v *float64) *EventOccurrenceCreate {
	if v != nil {
		_c.SetLongitude(*v)
	}
	return _c
}

// SetCoordinateSource sets the "coordinate_source" field.
func (_c *EventOccurrenceCreate) SetCoordinateSource(v string) *EventOccurrenceCreate {
	_c.mutation.SetCoordinateSource(v)
	return _c
}

// SetNillableCoordinateSource sets the "coordinate_source" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableCoordinateSource(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetCoordinateSource(*v)
	}
	return _c
}

// SetGeocodeStatus sets the "geocode_status" field.
func (_c *EventOccurrenceCreate) SetGeocodeStatus(v string) *EventOccurrenceCreate {
	_c.mutation.SetGeocodeStatus(v)
	return _c
}

// SetNillableGeocodeStatus sets the "geocode_status" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableGeocodeStatus(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetGeocodeStatus(*v)
	}
	return _c
}

// SetGeocodePrecision sets the "geocode_precision" field.
func (_c *EventOccurrenceCreate) SetGeocodePrecision(v string) *EventOccurrenceCreate {
	_c.mutation.SetGeocodePrecision(v)
	return _c
}

// SetNillableGeocodePrecision sets the "geocode_precision" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableGeocodePrecision(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetGeocodePrecision(*v)
	}
	return _c
}

// SetProviderPlaceID sets the "provider_place_id" field.
func (_c *EventOccurrenceCreate) SetProviderPlaceID(v string) *EventOccurrenceCreate {
	_c.mutation.SetProviderPlaceID(v)
	return _c
}

// SetNillableProviderPlaceID sets the "provider_place_id" field if the given value is not nil.
func (_c *EventOccurrenceCreate) SetNillableProviderPlaceID(v *string) *EventOccurrenceCreate {
	if v != nil {
		_c.SetProviderPlaceID(*v)
	}
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *EventOccurrenceCreate) SetEvent(v *Event) *EventOccurrenceCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the EventOccurrenceMutation object of the builder.
func (_c *EventOccurrenceCreate) Mutation() *EventOccurrenceMutation {
	return _c.mutation
}

// Save creates the EventOccurrence in the database.
func (_c *EventOccurrenceCreate) Save(ctx context.Context) (*EventOccurrence, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventOccurrenceCreate) SaveX(ctx context.Context) *EventOccurrence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventOccurrenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventOccurrenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventOccurrenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := eventoccurrence.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := eventoccurrence.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := eventoccurrence.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.AllDay(); !ok {
		v := eventoccurrence.DefaultAllDay
		_c.mutation.SetAllDay(v)
	}
	if _, ok := _c.mutation.LocationMode(); !ok {
		v := eventoccurrence.DefaultLocationMode
		_c.mutation.SetLocationMode(v)
	}
	if _, ok := _c.mutation.OnlineURL(); !ok {
		v := eventoccurrence.DefaultOnlineURL
		_c.mutation.SetOnlineURL(v)
	}
	if _, ok := _c.mutation.VenueName(); !ok {
		v := eventoccurrence.DefaultVenueName
		_c.mutation.SetVenueName(v)
	}
	if _, ok := _c.mutation.Address(); !ok {
		v := eventoccurrence.DefaultAddress
		_c.mutation.SetAddress(v)
	}
	if _, ok := _c.mutation.Country(); !ok {
		v := eventoccurrence.DefaultCountry
		_c.mutation.SetCountry(v)
	}
	if _, ok := _c.mutation.Province(); !ok {
		v := eventoccurrence.DefaultProvince
		_c.mutation.SetProvince(v)
	}
	if _, ok := _c.mutation.City(); !ok {
		v := eventoccurrence.DefaultCity
		_c.mutation.SetCity(v)
	}
	if _, ok := _c.mutation.District(); !ok {
		v := eventoccurrence.DefaultDistrict
		_c.mutation.SetDistrict(v)
	}
	if _, ok := _c.mutation.CoordinateSource(); !ok {
		v := eventoccurrence.DefaultCoordinateSource
		_c.mutation.SetCoordinateSource(v)
	}
	if _, ok := _c.mutation.GeocodeStatus(); !ok {
		v := eventoccurrence.DefaultGeocodeStatus
		_c.mutation.SetGeocodeStatus(v)
	}
	if _, ok := _c.mutation.GeocodePrecision(); !ok {
		v := eventoccurrence.DefaultGeocodePrecision
		_c.mutation.SetGeocodePrecision(v)
	}
	if _, ok := _c.mutation.ProviderPlaceID(); !ok {
		v := eventoccurrence.DefaultProviderPlaceID
		_c.mutation.SetProviderPlaceID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventOccurrenceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EventOccurrence.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EventOccurrence.updated_at"`)}
	}
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "EventOccurrence.event_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "EventOccurrence.starts_at"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "EventOccurrence.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := eventoccurrence.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllDay(); !ok {
		return &ValidationError{Name: "all_day", err: errors.New(`ent: missing required field "EventOccurrence.all_day"`)}
	}
	if _, ok := _c.mutation.LocationMode(); !ok {
		return &ValidationError{Name: "location_mode", err: errors.New(`ent: missing required field "EventOccurrence.location_mode"`)}
	}
	if v, ok := _c.mutation.LocationMode(); ok {
		if err := eventoccurrence.LocationModeValidator(v); err != nil {
			return &ValidationError{Name: "location_mode", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.location_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OnlineURL(); !ok {
		return &ValidationError{Name: "online_url", err: errors.New(`ent: missing required field "EventOccurrence.online_url"`)}
	}
	if v, ok := _c.mutation.OnlineURL(); ok {
		if err := eventoccurrence.OnlineURLValidator(v); err != nil {
			return &ValidationError{Name: "online_url", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.online_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VenueName(); !ok {
		return &ValidationError{Name: "venue_name", err: errors.New(`ent: missing required field "EventOccurrence.venue_name"`)}
	}
	if v, ok := _c.mutation.VenueName(); ok {
		if err := eventoccurrence.VenueNameValidator(v); err != nil {
			return &ValidationError{Name: "venue_name", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.venue_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "EventOccurrence.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := eventoccurrence.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "EventOccurrence.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := eventoccurrence.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Province(); !ok {
		return &ValidationError{Name: "province", err: errors.New(`ent: missing required field "EventOccurrence.province"`)}
	}
	if v, ok := _c.mutation.Province(); ok {
		if err := eventoccurrence.ProvinceValidator(v); err != nil {
			return &ValidationError{Name: "province", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.province": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "EventOccurrence.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := eventoccurrence.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.District(); !ok {
		return &ValidationError{Name: "district", err: errors.New(`ent: missing required field "EventOccurrence.district"`)}
	}
	if v, ok := _c.mutation.District(); ok {
		if err := eventoccurrence.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.district": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CoordinateSource(); !ok {
		return &ValidationError{Name: "coordinate_source", err: errors.New(`ent: missing required field "EventOccurrence.coordinate_source"`)}
	}
	if v, ok := _c.mutation.CoordinateSource(); ok {
		if err := eventoccurrence.CoordinateSourceValidator(v); err != nil {
			return &ValidationError{Name: "coordinate_source", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.coordinate_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GeocodeStatus(); !ok {
		return &ValidationError{Name: "geocode_status", err: errors.New(`ent: missing required field "EventOccurrence.geocode_status"`)}
	}
	if v, ok := _c.mutation.GeocodeStatus(); ok {
		if err := eventoccurrence.GeocodeStatusValidator(v); err != nil {
			return &ValidationError{Name: "geocode_status", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.geocode_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GeocodePrecision(); !ok {
		return &ValidationError{Name: "geocode_precision", err: errors.New(`ent: missing required field "EventOccurrence.geocode_precision"`)}
	}
	if v, ok := _c.mutation.GeocodePrecision(); ok {
		if err := eventoccurrence.GeocodePrecisionValidator(v); err != nil {
			return &ValidationError{Name: "geocode_precision", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.geocode_precision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderPlaceID(); !ok {
		return &ValidationError{Name: "provider_place_id", err: errors.New(`ent: missing required field "EventOccurrence.provider_place_id"`)}
	}
	if v, ok := _c.mutation.ProviderPlaceID(); ok {
		if err := eventoccurrence.ProviderPlaceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_place_id", err: fmt.Errorf(`ent: validator failed for field "EventOccurrence.provider_place_id": %w`, err)}
		}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "EventOccurrence.event"`)}
	}
	return nil
}

func (_c *EventOccurrenceCreate) sqlSave(ctx context.Context) (*EventOccurrence, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventOccurrenceCreate) createSpec() (*EventOccurrence, *sqlgraph.CreateSpec) {
	var (
		_node = &EventOccurrence{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventoccurrence.Table, sqlgraph.NewFieldSpec(eventoccurrence.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(eventoccurrence.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(eventoccurrence.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(eventoccurrence.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(eventoccurrence.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = &value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(eventoccurrence.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.AllDay(); ok {
		_spec.SetField(eventoccurrence.FieldAllDay, field.TypeBool, value)
		_node.AllDay = value
	}
	if value, ok := _c.mutation.LocationMode(); ok {
		_spec.SetField(eventoccurrence.FieldLocationMode, field.TypeString, value)
		_node.LocationMode = value
	}
	if value, ok := _c.mutation.OnlineURL(); ok {
		_spec.SetField(eventoccurrence.FieldOnlineURL, field.TypeString, value)
		_node.OnlineURL = value
	}
	if value, ok := _c.mutation.VenueName(); ok {
		_spec.SetField(eventoccurrence.FieldVenueName, field.TypeString, value)
		_node.VenueName = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(eventoccurrence.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(eventoccurrence.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Province(); ok {
		_spec.SetField(eventoccurrence.FieldProvince, field.TypeString, value)
		_node.Province = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(eventoccurrence.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.District(); ok {
		_spec.SetField(eventoccurrence.FieldDistrict, field.TypeString, value)
		_node.District = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(eventoccurrence.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = &value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(eventoccurrence.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = &value
	}
	if value, ok := _c.mutation.CoordinateSource(); ok {
		_spec.SetField(eventoccurrence.FieldCoordinateSource, field.TypeString, value)
		_node.CoordinateSource = value
	}
	if value, ok := _c.mutation.GeocodeStatus(); ok {
		_spec.SetField(eventoccurrence.FieldGeocodeStatus, field.TypeString, value)
		_node.GeocodeStatus = value
	}
	if value, ok := _c.mutation.GeocodePrecision(); ok {
		_spec.SetField(eventoccurrence.FieldGeocodePrecision, field.TypeString, value)
		_node.GeocodePrecision = value
	}
	if value, ok := _c.mutation.ProviderPlaceID(); ok {
		_spec.SetField(eventoccurrence.FieldProviderPlaceID, field.TypeString, value)
		_node.ProviderPlaceID = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventoccurrence.EventTable,
			Columns: []string{eventoccurrence.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EventOccurrence.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventOccurrenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventOccurrenceCreate) OnConflict(opts ...sql.ConflictOption) *EventOccurrenceUpsertOne {
	_c.conflict = opts
	return &EventOccurrenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EventOccurrence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventOccurrenceCreate) OnConflictColumns(columns ...string) *EventOccurrenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventOccurrenceUpsertOne{
		create: _c,
	}
}

type (
	// EventOccurrenceUpsertOne is the builder for "upsert"-ing
	//  one EventOccurrence node.
	EventOccurrenceUpsertOne struct {
		create *EventOccurrenceCreate
	}

	// EventOccurrenceUpsert is the "OnConflict" setter.
	EventOccurrenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EventOccurrenceUpsert) SetUpdatedAt(v time.Time) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateUpdatedAt() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldUpdatedAt)
	return u
}

// SetEventID sets the "event_id" field.
func (u *EventOccurrenceUpsert) SetEventID(v int64) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldEventID, v)
	return u
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateEventID() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldEventID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *EventOccurrenceUpsert) SetStartsAt(v time.Time) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateStartsAt() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *EventOccurrenceUpsert) SetEndsAt(v time.Time) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateEndsAt() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldEndsAt)
	return u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *EventOccurrenceUpsert) ClearEndsAt() *EventOccurrenceUpsert {
	u.SetNull(eventoccurrence.FieldEndsAt)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *EventOccurrenceUpsert) SetTimezone(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateTimezone() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldTimezone)
	return u
}

// SetAllDay sets the "all_day" field.
func (u *EventOccurrenceUpsert) SetAllDay(v bool) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldAllDay, v)
	return u
}

// UpdateAllDay sets the "all_day" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateAllDay() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldAllDay)
	return u
}

// SetLocationMode sets the "location_mode" field.
func (u *EventOccurrenceUpsert) SetLocationMode(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldLocationMode, v)
	return u
}

// UpdateLocationMode sets the "location_mode" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateLocationMode() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldLocationMode)
	return u
}

// SetOnlineURL sets the "online_url" field.
func (u *EventOccurrenceUpsert) SetOnlineURL(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldOnlineURL, v)
	return u
}

// UpdateOnlineURL sets the "online_url" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateOnlineURL() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldOnlineURL)
	return u
}

// SetVenueName sets the "venue_name" field.
func (u *EventOccurrenceUpsert) SetVenueName(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldVenueName, v)
	return u
}

// UpdateVenueName sets the "venue_name" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateVenueName() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldVenueName)
	return u
}

// SetAddress sets the "address" field.
func (u *EventOccurrenceUpsert) SetAddress(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateAddress() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldAddress)
	return u
}

// SetCountry sets the "country" field.
func (u *EventOccurrenceUpsert) SetCountry(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldCountry, v)
	return u
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateCountry() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldCountry)
	return u
}

// SetProvince sets the "province" field.
func (u *EventOccurrenceUpsert) SetProvince(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldProvince, v)
	return u
}

// UpdateProvince sets the "province" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateProvince() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldProvince)
	return u
}

// SetCity sets the "city" field.
func (u *EventOccurrenceUpsert) SetCity(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldCity, v)
	return u
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateCity() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldCity)
	return u
}

// SetDistrict sets the "district" field.
func (u *EventOccurrenceUpsert) SetDistrict(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldDistrict, v)
	return u
}

// UpdateDistrict sets the "district" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateDistrict() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldDistrict)
	return u
}

// SetLatitude sets the "latitude" field.
func (u *EventOccurrenceUpsert) SetLatitude(v float64) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldLatitude, v)
	return u
}

// UpdateLatitude sets the "latitude" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateLatitude() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldLatitude)
	return u
}

// AddLatitude adds v to the "latitude" field.
func (u *EventOccurrenceUpsert) AddLatitude(v float64) *EventOccurrenceUpsert {
	u.Add(eventoccurrence.FieldLatitude, v)
	return u
}

// ClearLatitude clears the value of the "latitude" field.
func (u *EventOccurrenceUpsert) ClearLatitude() *EventOccurrenceUpsert {
	u.SetNull(eventoccurrence.FieldLatitude)
	return u
}

// SetLongitude sets the "longitude" field.
func (u *EventOccurrenceUpsert) SetLongitude(v float64) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldLongitude, v)
	return u
}

// UpdateLongitude sets the "longitude" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateLongitude() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldLongitude)
	return u
}

// AddLongitude adds v to the "longitude" field.
func (u *EventOccurrenceUpsert) AddLongitude(v float64) *EventOccurrenceUpsert {
	u.Add(eventoccurrence.FieldLongitude, v)
	return u
}

// ClearLongitude clears the value of the "longitude" field.
func (u *EventOccurrenceUpsert) ClearLongitude() *EventOccurrenceUpsert {
	u.SetNull(eventoccurrence.FieldLongitude)
	return u
}

// SetCoordinateSource sets the "coordinate_source" field.
func (u *EventOccurrenceUpsert) SetCoordinateSource(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldCoordinateSource, v)
	return u
}

// UpdateCoordinateSource sets the "coordinate_source" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateCoordinateSource() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldCoordinateSource)
	return u
}

// SetGeocodeStatus sets the "geocode_status" field.
func (u *EventOccurrenceUpsert) SetGeocodeStatus(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldGeocodeStatus, v)
	return u
}

// UpdateGeocodeStatus sets the "geocode_status" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateGeocodeStatus() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldGeocodeStatus)
	return u
}

// SetGeocodePrecision sets the "geocode_precision" field.
func (u *EventOccurrenceUpsert) SetGeocodePrecision(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldGeocodePrecision, v)
	return u
}

// UpdateGeocodePrecision sets the "geocode_precision" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateGeocodePrecision() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldGeocodePrecision)
	return u
}

// SetProviderPlaceID sets the "provider_place_id" field.
func (u *EventOccurrenceUpsert) SetProviderPlaceID(v string) *EventOccurrenceUpsert {
	u.Set(eventoccurrence.FieldProviderPlaceID, v)
	return u
}

// UpdateProviderPlaceID sets the "provider_place_id" field to the value that was provided on create.
func (u *EventOccurrenceUpsert) UpdateProviderPlaceID() *EventOccurrenceUpsert {
	u.SetExcluded(eventoccurrence.FieldProviderPlaceID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EventOccurrence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventOccurrenceUpsertOne) UpdateNewValues() *EventOccurrenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(eventoccurrence.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EventOccurrence.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EventOccurrenceUpsertOne) Ignore() *EventOccurrenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventOccurrenceUpsertOne) DoNothing() *EventOccurrenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventOccurrenceCreate.OnConflict
// documentation for more info.
func (u *EventOccurrenceUpsertOne) Update(set func(*EventOccurrenceUpsert)) *EventOccurrenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventOccurrenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventOccurrenceUpsertOne) SetUpdatedAt(v time.Time) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateUpdatedAt() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEventID sets the "event_id" field.
func (u *EventOccurrenceUpsertOne) SetEventID(v int64) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateEventID() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateEventID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *EventOccurrenceUpsertOne) SetStartsAt(v time.Time) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateStartsAt() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *EventOccurrenceUpsertOne) SetEndsAt(v time.Time) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateEndsAt() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *EventOccurrenceUpsertOne) ClearEndsAt() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.ClearEndsAt()
	})
}

// SetTimezone sets the "timezone" field.
func (u *EventOccurrenceUpsertOne) SetTimezone(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateTimezone() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateTimezone()
	})
}

// SetAllDay sets the "all_day" field.
func (u *EventOccurrenceUpsertOne) SetAllDay(v bool) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetAllDay(v)
	})
}

// UpdateAllDay sets the "all_day" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateAllDay() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateAllDay()
	})
}

// SetLocationMode sets the "location_mode" field.
func (u *EventOccurrenceUpsertOne) SetLocationMode(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetLocationMode(v)
	})
}

// UpdateLocationMode sets the "location_mode" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateLocationMode() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateLocationMode()
	})
}

// SetOnlineURL sets the "online_url" field.
func (u *EventOccurrenceUpsertOne) SetOnlineURL(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetOnlineURL(v)
	})
}

// UpdateOnlineURL sets the "online_url" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateOnlineURL() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateOnlineURL()
	})
}

// SetVenueName sets the "venue_name" field.
func (u *EventOccurrenceUpsertOne) SetVenueName(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetVenueName(v)
	})
}

// UpdateVenueName sets the "venue_name" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateVenueName() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateVenueName()
	})
}

// SetAddress sets the "address" field.
func (u *EventOccurrenceUpsertOne) SetAddress(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateAddress() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateAddress()
	})
}

// SetCountry sets the "country" field.
func (u *EventOccurrenceUpsertOne) SetCountry(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateCountry() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateCountry()
	})
}

// SetProvince sets the "province" field.
func (u *EventOccurrenceUpsertOne) SetProvince(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetProvince(v)
	})
}

// UpdateProvince sets the "province" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateProvince() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateProvince()
	})
}

// SetCity sets the "city" field.
func (u *EventOccurrenceUpsertOne) SetCity(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateCity() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateCity()
	})
}

// SetDistrict sets the "district" field.
func (u *EventOccurrenceUpsertOne) SetDistrict(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetDistrict(v)
	})
}

// UpdateDistrict sets the "district" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateDistrict() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateDistrict()
	})
}

// SetLatitude sets the "latitude" field.
func (u *EventOccurrenceUpsertOne) SetLatitude(v float64) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetLatitude(v)
	})
}

// AddLatitude adds v to the "latitude" field.
func (u *EventOccurrenceUpsertOne) AddLatitude(v float64) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.AddLatitude(v)
	})
}

// UpdateLatitude sets the "latitude" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateLatitude() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateLatitude()
	})
}

// ClearLatitude clears the value of the "latitude" field.
func (u *EventOccurrenceUpsertOne) ClearLatitude() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.ClearLatitude()
	})
}

// SetLongitude sets the "longitude" field.
func (u *EventOccurrenceUpsertOne) SetLongitude(v float64) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetLongitude(v)
	})
}

// AddLongitude adds v to the "longitude" field.
func (u *EventOccurrenceUpsertOne) AddLongitude(v float64) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.AddLongitude(v)
	})
}

// UpdateLongitude sets the "longitude" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateLongitude() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateLongitude()
	})
}

// ClearLongitude clears the value of the "longitude" field.
func (u *EventOccurrenceUpsertOne) ClearLongitude() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.ClearLongitude()
	})
}

// SetCoordinateSource sets the "coordinate_source" field.
func (u *EventOccurrenceUpsertOne) SetCoordinateSource(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetCoordinateSource(v)
	})
}

// UpdateCoordinateSource sets the "coordinate_source" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateCoordinateSource() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateCoordinateSource()
	})
}

// SetGeocodeStatus sets the "geocode_status" field.
func (u *EventOccurrenceUpsertOne) SetGeocodeStatus(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetGeocodeStatus(v)
	})
}

// UpdateGeocodeStatus sets the "geocode_status" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateGeocodeStatus() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateGeocodeStatus()
	})
}

// SetGeocodePrecision sets the "geocode_precision" field.
func (u *EventOccurrenceUpsertOne) SetGeocodePrecision(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetGeocodePrecision(v)
	})
}

// UpdateGeocodePrecision sets the "geocode_precision" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateGeocodePrecision() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateGeocodePrecision()
	})
}

// SetProviderPlaceID sets the "provider_place_id" field.
func (u *EventOccurrenceUpsertOne) SetProviderPlaceID(v string) *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetProviderPlaceID(v)
	})
}

// UpdateProviderPlaceID sets the "provider_place_id" field to the value that was provided on create.
func (u *EventOccurrenceUpsertOne) UpdateProviderPlaceID() *EventOccurrenceUpsertOne {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateProviderPlaceID()
	})
}

// Exec executes the query.
func (u *EventOccurrenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventOccurrenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventOccurrenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EventOccurrenceUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EventOccurrenceUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EventOccurrenceCreateBulk is the builder for creating many EventOccurrence entities in bulk.
type EventOccurrenceCreateBulk struct {
	config
	err      error
	builders []*EventOccurrenceCreate
	conflict []sql.ConflictOption
}

// Save creates the EventOccurrence entities in the database.
func (_c *EventOccurrenceCreateBulk) Save(ctx context.Context) ([]*EventOccurrence, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventOccurrence, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventOccurrenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventOccurrenceCreateBulk) SaveX(ctx context.Context) []*EventOccurrence {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventOccurrenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventOccurrenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EventOccurrence.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventOccurrenceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EventOccurrenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *EventOccurrenceUpsertBulk {
	_c.conflict = opts
	return &EventOccurrenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EventOccurrence.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventOccurrenceCreateBulk) OnConflictColumns(columns ...string) *EventOccurrenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventOccurrenceUpsertBulk{
		create: _c,
	}
}

// EventOccurrenceUpsertBulk is the builder for "upsert"-ing
// a bulk of EventOccurrence nodes.
type EventOccurrenceUpsertBulk struct {
	create *EventOccurrenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EventOccurrence.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventOccurrenceUpsertBulk) UpdateNewValues() *EventOccurrenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(eventoccurrence.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EventOccurrence.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EventOccurrenceUpsertBulk) Ignore() *EventOccurrenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventOccurrenceUpsertBulk) DoNothing() *EventOccurrenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventOccurrenceCreateBulk.OnConflict
// documentation for more info.
func (u *EventOccurrenceUpsertBulk) Update(set func(*EventOccurrenceUpsert)) *EventOccurrenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventOccurrenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventOccurrenceUpsertBulk) SetUpdatedAt(v time.Time) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateUpdatedAt() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEventID sets the "event_id" field.
func (u *EventOccurrenceUpsertBulk) SetEventID(v int64) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateEventID() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateEventID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *EventOccurrenceUpsertBulk) SetStartsAt(v time.Time) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateStartsAt() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *EventOccurrenceUpsertBulk) SetEndsAt(v time.Time) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateEndsAt() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateEndsAt()
	})
}

// ClearEndsAt clears the value of the "ends_at" field.
func (u *EventOccurrenceUpsertBulk) ClearEndsAt() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.ClearEndsAt()
	})
}

// SetTimezone sets the "timezone" field.
func (u *EventOccurrenceUpsertBulk) SetTimezone(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateTimezone() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateTimezone()
	})
}

// SetAllDay sets the "all_day" field.
func (u *EventOccurrenceUpsertBulk) SetAllDay(v bool) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetAllDay(v)
	})
}

// UpdateAllDay sets the "all_day" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateAllDay() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateAllDay()
	})
}

// SetLocationMode sets the "location_mode" field.
func (u *EventOccurrenceUpsertBulk) SetLocationMode(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetLocationMode(v)
	})
}

// UpdateLocationMode sets the "location_mode" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateLocationMode() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateLocationMode()
	})
}

// SetOnlineURL sets the "online_url" field.
func (u *EventOccurrenceUpsertBulk) SetOnlineURL(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetOnlineURL(v)
	})
}

// UpdateOnlineURL sets the "online_url" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateOnlineURL() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateOnlineURL()
	})
}

// SetVenueName sets the "venue_name" field.
func (u *EventOccurrenceUpsertBulk) SetVenueName(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetVenueName(v)
	})
}

// UpdateVenueName sets the "venue_name" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateVenueName() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateVenueName()
	})
}

// SetAddress sets the "address" field.
func (u *EventOccurrenceUpsertBulk) SetAddress(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateAddress() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateAddress()
	})
}

// SetCountry sets the "country" field.
func (u *EventOccurrenceUpsertBulk) SetCountry(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateCountry() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateCountry()
	})
}

// SetProvince sets the "province" field.
func (u *EventOccurrenceUpsertBulk) SetProvince(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetProvince(v)
	})
}

// UpdateProvince sets the "province" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateProvince() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateProvince()
	})
}

// SetCity sets the "city" field.
func (u *EventOccurrenceUpsertBulk) SetCity(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateCity() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateCity()
	})
}

// SetDistrict sets the "district" field.
func (u *EventOccurrenceUpsertBulk) SetDistrict(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetDistrict(v)
	})
}

// UpdateDistrict sets the "district" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateDistrict() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateDistrict()
	})
}

// SetLatitude sets the "latitude" field.
func (u *EventOccurrenceUpsertBulk) SetLatitude(v float64) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetLatitude(v)
	})
}

// AddLatitude adds v to the "latitude" field.
func (u *EventOccurrenceUpsertBulk) AddLatitude(v float64) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.AddLatitude(v)
	})
}

// UpdateLatitude sets the "latitude" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateLatitude() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateLatitude()
	})
}

// ClearLatitude clears the value of the "latitude" field.
func (u *EventOccurrenceUpsertBulk) ClearLatitude() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.ClearLatitude()
	})
}

// SetLongitude sets the "longitude" field.
func (u *EventOccurrenceUpsertBulk) SetLongitude(v float64) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetLongitude(v)
	})
}

// AddLongitude adds v to the "longitude" field.
func (u *EventOccurrenceUpsertBulk) AddLongitude(v float64) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.AddLongitude(v)
	})
}

// UpdateLongitude sets the "longitude" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateLongitude() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateLongitude()
	})
}

// ClearLongitude clears the value of the "longitude" field.
func (u *EventOccurrenceUpsertBulk) ClearLongitude() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.ClearLongitude()
	})
}

// SetCoordinateSource sets the "coordinate_source" field.
func (u *EventOccurrenceUpsertBulk) SetCoordinateSource(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetCoordinateSource(v)
	})
}

// UpdateCoordinateSource sets the "coordinate_source" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateCoordinateSource() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateCoordinateSource()
	})
}

// SetGeocodeStatus sets the "geocode_status" field.
func (u *EventOccurrenceUpsertBulk) SetGeocodeStatus(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetGeocodeStatus(v)
	})
}

// UpdateGeocodeStatus sets the "geocode_status" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateGeocodeStatus() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateGeocodeStatus()
	})
}

// SetGeocodePrecision sets the "geocode_precision" field.
func (u *EventOccurrenceUpsertBulk) SetGeocodePrecision(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetGeocodePrecision(v)
	})
}

// UpdateGeocodePrecision sets the "geocode_precision" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateGeocodePrecision() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateGeocodePrecision()
	})
}

// SetProviderPlaceID sets the "provider_place_id" field.
func (u *EventOccurrenceUpsertBulk) SetProviderPlaceID(v string) *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.SetProviderPlaceID(v)
	})
}

// UpdateProviderPlaceID sets the "provider_place_id" field to the value that was provided on create.
func (u *EventOccurrenceUpsertBulk) UpdateProviderPlaceID() *EventOccurrenceUpsertBulk {
	return u.Update(func(s *EventOccurrenceUpsert) {
		s.UpdateProviderPlaceID()
	})
}

// Exec executes the query.
func (u *EventOccurrenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EventOccurrenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventOccurrenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventOccurrenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
