// Code generated by ent, DO NOT EDIT.

package eventoccurrence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldUpdatedAt, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldEventID, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldEndsAt, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldTimezone, v))
}

// AllDay applies equality check predicate on the "all_day" field. It's identical to AllDayEQ.
func AllDay(v bool) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldAllDay, v))
}

// LocationMode applies equality check predicate on the "location_mode" field. It's identical to LocationModeEQ.
func LocationMode(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldLocationMode, v))
}

// OnlineURL applies equality check predicate on the "online_url" field. It's identical to OnlineURLEQ.
func OnlineURL(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldOnlineURL, v))
}

// VenueName applies equality check predicate on the "venue_name" field. It's identical to VenueNameEQ.
func VenueName(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldVenueName, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldAddress, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCountry, v))
}

// Province applies equality check predicate on the "province" field. It's identical to ProvinceEQ.
func Province(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldProvince, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCity, v))
}

// District applies equality check predicate on the "district" field. It's identical to DistrictEQ.
func District(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldDistrict, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldLongitude, v))
}

// CoordinateSource applies equality check predicate on the "coordinate_source" field. It's identical to CoordinateSourceEQ.
func CoordinateSource(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCoordinateSource, v))
}

// GeocodeStatus applies equality check predicate on the "geocode_status" field. It's identical to GeocodeStatusEQ.
func GeocodeStatus(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldGeocodeStatus, v))
}

// GeocodePrecision applies equality check predicate on the "geocode_precision" field. It's identical to GeocodePrecisionEQ.
func GeocodePrecision(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldGeocodePrecision, v))
}

// ProviderPlaceID applies equality check predicate on the "provider_place_id" field. It's identical to ProviderPlaceIDEQ.
func ProviderPlaceID(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldProviderPlaceID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldUpdatedAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...int64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldEventID, vs...))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldStartsAt, v))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldEndsAt, v))
}

// EndsAtIsNil applies the IsNil predicate on the "ends_at" field.
func EndsAtIsNil() predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIsNull(FieldEndsAt))
}

// EndsAtNotNil applies the NotNil predicate on the "ends_at" field.
func EndsAtNotNil() predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotNull(FieldEndsAt))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldTimezone, v))
}

// AllDayEQ applies the EQ predicate on the "all_day" field.
func AllDayEQ(v bool) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldAllDay, v))
}

// AllDayNEQ applies the NEQ predicate on the "all_day" field.
func AllDayNEQ(v bool) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldAllDay, v))
}

// LocationModeEQ applies the EQ predicate on the "location_mode" field.
func LocationModeEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldLocationMode, v))
}

// LocationModeNEQ applies the NEQ predicate on the "location_mode" field.
func LocationModeNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldLocationMode, v))
}

// LocationModeIn applies the In predicate on the "location_mode" field.
func LocationModeIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldLocationMode, vs...))
}

// LocationModeNotIn applies the NotIn predicate on the "location_mode" field.
func LocationModeNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldLocationMode, vs...))
}

// LocationModeGT applies the GT predicate on the "location_mode" field.
func LocationModeGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldLocationMode, v))
}

// LocationModeGTE applies the GTE predicate on the "location_mode" field.
func LocationModeGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldLocationMode, v))
}

// LocationModeLT applies the LT predicate on the "location_mode" field.
func LocationModeLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldLocationMode, v))
}

// LocationModeLTE applies the LTE predicate on the "location_mode" field.
func LocationModeLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldLocationMode, v))
}

// LocationModeContains applies the Contains predicate on the "location_mode" field.
func LocationModeContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldLocationMode, v))
}

// LocationModeHasPrefix applies the HasPrefix predicate on the "location_mode" field.
func LocationModeHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldLocationMode, v))
}

// LocationModeHasSuffix applies the HasSuffix predicate on the "location_mode" field.
func LocationModeHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldLocationMode, v))
}

// LocationModeEqualFold applies the EqualFold predicate on the "location_mode" field.
func LocationModeEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldLocationMode, v))
}

// LocationModeContainsFold applies the ContainsFold predicate on the "location_mode" field.
func LocationModeContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldLocationMode, v))
}

// OnlineURLEQ applies the EQ predicate on the "online_url" field.
func OnlineURLEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldOnlineURL, v))
}

// OnlineURLNEQ applies the NEQ predicate on the "online_url" field.
func OnlineURLNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldOnlineURL, v))
}

// OnlineURLIn applies the In predicate on the "online_url" field.
func OnlineURLIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldOnlineURL, vs...))
}

// OnlineURLNotIn applies the NotIn predicate on the "online_url" field.
func OnlineURLNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldOnlineURL, vs...))
}

// OnlineURLGT applies the GT predicate on the "online_url" field.
func OnlineURLGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldOnlineURL, v))
}

// OnlineURLGTE applies the GTE predicate on the "online_url" field.
func OnlineURLGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldOnlineURL, v))
}

// OnlineURLLT applies the LT predicate on the "online_url" field.
func OnlineURLLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldOnlineURL, v))
}

// OnlineURLLTE applies the LTE predicate on the "online_url" field.
func OnlineURLLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldOnlineURL, v))
}

// OnlineURLContains applies the Contains predicate on the "online_url" field.
func OnlineURLContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldOnlineURL, v))
}

// OnlineURLHasPrefix applies the HasPrefix predicate on the "online_url" field.
func OnlineURLHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldOnlineURL, v))
}

// OnlineURLHasSuffix applies the HasSuffix predicate on the "online_url" field.
func OnlineURLHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldOnlineURL, v))
}

// OnlineURLEqualFold applies the EqualFold predicate on the "online_url" field.
func OnlineURLEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldOnlineURL, v))
}

// OnlineURLContainsFold applies the ContainsFold predicate on the "online_url" field.
func OnlineURLContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldOnlineURL, v))
}

// VenueNameEQ applies the EQ predicate on the "venue_name" field.
func VenueNameEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldVenueName, v))
}

// VenueNameNEQ applies the NEQ predicate on the "venue_name" field.
func VenueNameNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldVenueName, v))
}

// VenueNameIn applies the In predicate on the "venue_name" field.
func VenueNameIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldVenueName, vs...))
}

// VenueNameNotIn applies the NotIn predicate on the "venue_name" field.
func VenueNameNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldVenueName, vs...))
}

// VenueNameGT applies the GT predicate on the "venue_name" field.
func VenueNameGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldVenueName, v))
}

// VenueNameGTE applies the GTE predicate on the "venue_name" field.
func VenueNameGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldVenueName, v))
}

// VenueNameLT applies the LT predicate on the "venue_name" field.
func VenueNameLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldVenueName, v))
}

// VenueNameLTE applies the LTE predicate on the "venue_name" field.
func VenueNameLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldVenueName, v))
}

// VenueNameContains applies the Contains predicate on the "venue_name" field.
func VenueNameContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldVenueName, v))
}

// VenueNameHasPrefix applies the HasPrefix predicate on the "venue_name" field.
func VenueNameHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldVenueName, v))
}

// VenueNameHasSuffix applies the HasSuffix predicate on the "venue_name" field.
func VenueNameHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldVenueName, v))
}

// VenueNameEqualFold applies the EqualFold predicate on the "venue_name" field.
func VenueNameEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldVenueName, v))
}

// VenueNameContainsFold applies the ContainsFold predicate on the "venue_name" field.
func VenueNameContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldVenueName, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldAddress, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldCountry, v))
}

// ProvinceEQ applies the EQ predicate on the "province" field.
func ProvinceEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldProvince, v))
}

// ProvinceNEQ applies the NEQ predicate on the "province" field.
func ProvinceNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldProvince, v))
}

// ProvinceIn applies the In predicate on the "province" field.
func ProvinceIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldProvince, vs...))
}

// ProvinceNotIn applies the NotIn predicate on the "province" field.
func ProvinceNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldProvince, vs...))
}

// ProvinceGT applies the GT predicate on the "province" field.
func ProvinceGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldProvince, v))
}

// ProvinceGTE applies the GTE predicate on the "province" field.
func ProvinceGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldProvince, v))
}

// ProvinceLT applies the LT predicate on the "province" field.
func ProvinceLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldProvince, v))
}

// ProvinceLTE applies the LTE predicate on the "province" field.
func ProvinceLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldProvince, v))
}

// ProvinceContains applies the Contains predicate on the "province" field.
func ProvinceContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldProvince, v))
}

// ProvinceHasPrefix applies the HasPrefix predicate on the "province" field.
func ProvinceHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldProvince, v))
}

// ProvinceHasSuffix applies the HasSuffix predicate on the "province" field.
func ProvinceHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldProvince, v))
}

// ProvinceEqualFold applies the EqualFold predicate on the "province" field.
func ProvinceEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldProvince, v))
}

// ProvinceContainsFold applies the ContainsFold predicate on the "province" field.
func ProvinceContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldProvince, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldCity, v))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldCity, v))
}

// DistrictEQ applies the EQ predicate on the "district" field.
func DistrictEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldDistrict, v))
}

// DistrictNEQ applies the NEQ predicate on the "district" field.
func DistrictNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldDistrict, v))
}

// DistrictIn applies the In predicate on the "district" field.
func DistrictIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldDistrict, vs...))
}

// DistrictNotIn applies the NotIn predicate on the "district" field.
func DistrictNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldDistrict, vs...))
}

// DistrictGT applies the GT predicate on the "district" field.
func DistrictGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldDistrict, v))
}

// DistrictGTE applies the GTE predicate on the "district" field.
func DistrictGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldDistrict, v))
}

// DistrictLT applies the LT predicate on the "district" field.
func DistrictLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldDistrict, v))
}

// DistrictLTE applies the LTE predicate on the "district" field.
func DistrictLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldDistrict, v))
}

// DistrictContains applies the Contains predicate on the "district" field.
func DistrictContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldDistrict, v))
}

// DistrictHasPrefix applies the HasPrefix predicate on the "district" field.
func DistrictHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldDistrict, v))
}

// DistrictHasSuffix applies the HasSuffix predicate on the "district" field.
func DistrictHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldDistrict, v))
}

// DistrictEqualFold applies the EqualFold predicate on the "district" field.
func DistrictEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldDistrict, v))
}

// DistrictContainsFold applies the ContainsFold predicate on the "district" field.
func DistrictContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldDistrict, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldLatitude, v))
}

// LatitudeIsNil applies the IsNil predicate on the "latitude" field.
func LatitudeIsNil() predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIsNull(FieldLatitude))
}

// LatitudeNotNil applies the NotNil predicate on the "latitude" field.
func LatitudeNotNil() predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotNull(FieldLatitude))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldLongitude, v))
}

// LongitudeIsNil applies the IsNil predicate on the "longitude" field.
func LongitudeIsNil() predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIsNull(FieldLongitude))
}

// LongitudeNotNil applies the NotNil predicate on the "longitude" field.
func LongitudeNotNil() predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotNull(FieldLongitude))
}

// CoordinateSourceEQ applies the EQ predicate on the "coordinate_source" field.
func CoordinateSourceEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldCoordinateSource, v))
}

// CoordinateSourceNEQ applies the NEQ predicate on the "coordinate_source" field.
func CoordinateSourceNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldCoordinateSource, v))
}

// CoordinateSourceIn applies the In predicate on the "coordinate_source" field.
func CoordinateSourceIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldCoordinateSource, vs...))
}

// CoordinateSourceNotIn applies the NotIn predicate on the "coordinate_source" field.
func CoordinateSourceNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldCoordinateSource, vs...))
}

// CoordinateSourceGT applies the GT predicate on the "coordinate_source" field.
func CoordinateSourceGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldCoordinateSource, v))
}

// CoordinateSourceGTE applies the GTE predicate on the "coordinate_source" field.
func CoordinateSourceGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldCoordinateSource, v))
}

// CoordinateSourceLT applies the LT predicate on the "coordinate_source" field.
func CoordinateSourceLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldCoordinateSource, v))
}

// CoordinateSourceLTE applies the LTE predicate on the "coordinate_source" field.
func CoordinateSourceLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldCoordinateSource, v))
}

// CoordinateSourceContains applies the Contains predicate on the "coordinate_source" field.
func CoordinateSourceContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldCoordinateSource, v))
}

// CoordinateSourceHasPrefix applies the HasPrefix predicate on the "coordinate_source" field.
func CoordinateSourceHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldCoordinateSource, v))
}

// CoordinateSourceHasSuffix applies the HasSuffix predicate on the "coordinate_source" field.
func CoordinateSourceHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldCoordinateSource, v))
}

// CoordinateSourceEqualFold applies the EqualFold predicate on the "coordinate_source" field.
func CoordinateSourceEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldCoordinateSource, v))
}

// CoordinateSourceContainsFold applies the ContainsFold predicate on the "coordinate_source" field.
func CoordinateSourceContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldCoordinateSource, v))
}

// GeocodeStatusEQ applies the EQ predicate on the "geocode_status" field.
func GeocodeStatusEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldGeocodeStatus, v))
}

// GeocodeStatusNEQ applies the NEQ predicate on the "geocode_status" field.
func GeocodeStatusNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldGeocodeStatus, v))
}

// GeocodeStatusIn applies the In predicate on the "geocode_status" field.
func GeocodeStatusIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldGeocodeStatus, vs...))
}

// GeocodeStatusNotIn applies the NotIn predicate on the "geocode_status" field.
func GeocodeStatusNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldGeocodeStatus, vs...))
}

// GeocodeStatusGT applies the GT predicate on the "geocode_status" field.
func GeocodeStatusGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldGeocodeStatus, v))
}

// GeocodeStatusGTE applies the GTE predicate on the "geocode_status" field.
func GeocodeStatusGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldGeocodeStatus, v))
}

// GeocodeStatusLT applies the LT predicate on the "geocode_status" field.
func GeocodeStatusLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldGeocodeStatus, v))
}

// GeocodeStatusLTE applies the LTE predicate on the "geocode_status" field.
func GeocodeStatusLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldGeocodeStatus, v))
}

// GeocodeStatusContains applies the Contains predicate on the "geocode_status" field.
func GeocodeStatusContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldGeocodeStatus, v))
}

// GeocodeStatusHasPrefix applies the HasPrefix predicate on the "geocode_status" field.
func GeocodeStatusHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldGeocodeStatus, v))
}

// GeocodeStatusHasSuffix applies the HasSuffix predicate on the "geocode_status" field.
func GeocodeStatusHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldGeocodeStatus, v))
}

// GeocodeStatusEqualFold applies the EqualFold predicate on the "geocode_status" field.
func GeocodeStatusEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldGeocodeStatus, v))
}

// GeocodeStatusContainsFold applies the ContainsFold predicate on the "geocode_status" field.
func GeocodeStatusContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldGeocodeStatus, v))
}

// GeocodePrecisionEQ applies the EQ predicate on the "geocode_precision" field.
func GeocodePrecisionEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldGeocodePrecision, v))
}

// GeocodePrecisionNEQ applies the NEQ predicate on the "geocode_precision" field.
func GeocodePrecisionNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldGeocodePrecision, v))
}

// GeocodePrecisionIn applies the In predicate on the "geocode_precision" field.
func GeocodePrecisionIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldGeocodePrecision, vs...))
}

// GeocodePrecisionNotIn applies the NotIn predicate on the "geocode_precision" field.
func GeocodePrecisionNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldGeocodePrecision, vs...))
}

// GeocodePrecisionGT applies the GT predicate on the "geocode_precision" field.
func GeocodePrecisionGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldGeocodePrecision, v))
}

// GeocodePrecisionGTE applies the GTE predicate on the "geocode_precision" field.
func GeocodePrecisionGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldGeocodePrecision, v))
}

// GeocodePrecisionLT applies the LT predicate on the "geocode_precision" field.
func GeocodePrecisionLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldGeocodePrecision, v))
}

// GeocodePrecisionLTE applies the LTE predicate on the "geocode_precision" field.
func GeocodePrecisionLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldGeocodePrecision, v))
}

// GeocodePrecisionContains applies the Contains predicate on the "geocode_precision" field.
func GeocodePrecisionContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldGeocodePrecision, v))
}

// GeocodePrecisionHasPrefix applies the HasPrefix predicate on the "geocode_precision" field.
func GeocodePrecisionHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldGeocodePrecision, v))
}

// GeocodePrecisionHasSuffix applies the HasSuffix predicate on the "geocode_precision" field.
func GeocodePrecisionHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldGeocodePrecision, v))
}

// GeocodePrecisionEqualFold applies the EqualFold predicate on the "geocode_precision" field.
func GeocodePrecisionEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldGeocodePrecision, v))
}

// GeocodePrecisionContainsFold applies the ContainsFold predicate on the "geocode_precision" field.
func GeocodePrecisionContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldGeocodePrecision, v))
}

// ProviderPlaceIDEQ applies the EQ predicate on the "provider_place_id" field.
func ProviderPlaceIDEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEQ(FieldProviderPlaceID, v))
}

// ProviderPlaceIDNEQ applies the NEQ predicate on the "provider_place_id" field.
func ProviderPlaceIDNEQ(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNEQ(FieldProviderPlaceID, v))
}

// ProviderPlaceIDIn applies the In predicate on the "provider_place_id" field.
func ProviderPlaceIDIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldIn(FieldProviderPlaceID, vs...))
}

// ProviderPlaceIDNotIn applies the NotIn predicate on the "provider_place_id" field.
func ProviderPlaceIDNotIn(vs ...string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldNotIn(FieldProviderPlaceID, vs...))
}

// ProviderPlaceIDGT applies the GT predicate on the "provider_place_id" field.
func ProviderPlaceIDGT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGT(FieldProviderPlaceID, v))
}

// ProviderPlaceIDGTE applies the GTE predicate on the "provider_place_id" field.
func ProviderPlaceIDGTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldGTE(FieldProviderPlaceID, v))
}

// ProviderPlaceIDLT applies the LT predicate on the "provider_place_id" field.
func ProviderPlaceIDLT(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLT(FieldProviderPlaceID, v))
}

// ProviderPlaceIDLTE applies the LTE predicate on the "provider_place_id" field.
func ProviderPlaceIDLTE(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldLTE(FieldProviderPlaceID, v))
}

// ProviderPlaceIDContains applies the Contains predicate on the "provider_place_id" field.
func ProviderPlaceIDContains(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContains(FieldProviderPlaceID, v))
}

// ProviderPlaceIDHasPrefix applies the HasPrefix predicate on the "provider_place_id" field.
func ProviderPlaceIDHasPrefix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasPrefix(FieldProviderPlaceID, v))
}

// ProviderPlaceIDHasSuffix applies the HasSuffix predicate on the "provider_place_id" field.
func ProviderPlaceIDHasSuffix(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldHasSuffix(FieldProviderPlaceID, v))
}

// ProviderPlaceIDEqualFold applies the EqualFold predicate on the "provider_place_id" field.
func ProviderPlaceIDEqualFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldEqualFold(FieldProviderPlaceID, v))
}

// ProviderPlaceIDContainsFold applies the ContainsFold predicate on the "provider_place_id" field.
func ProviderPlaceIDContainsFold(v string) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.FieldContainsFold(FieldProviderPlaceID, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.EventOccurrence {
	return predicate.EventOccurrence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.EventOccurrence {
	return predicate.EventOccurrence(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventOccurrence) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventOccurrence) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventOccurrence) predicate.EventOccurrence {
	return predicate.EventOccurrence(sql.NotPredicates(p))
}
